### ISSUE TITLE
It used to be MUCH easier to find tourist beacons when I was roaming the galaxy with the galaxy map

### ISSUE THREAD

**Issue by buzyperson** [njthomson/SrvSurvey#100]
In older versions, I was able to find nearby tourist beacons wherever I was in the galaxy on the 3D galaxy map. I had to do a little bit of hunting, but the task never took all that long.  However, the new 3D galaxy map in the current version has WAY more information, and there doesn't seem to be any way to filter on systems with tourist beacons. Could we have a filter just for systems with tourist beacons, or at least a special icon for those systems?

**Comment by buzyperson** [comment]
Sorry, wrong app.  goof me

**Comment by njthomson** [comment]
@buzyperson I am curious, which app did you mean?

**Comment by buzyperson** [comment]
EDDiscovery.
