### ISSUE TITLE
Wrong commander or game not active

### ISSUE THREAD

**Issue by SkepticalFall** [njthomson/SrvSurvey#101]
On log out of the game, the app says "Wrong commander or game not active". When restarting the game, it never changes and the app doesn't function until I restart the app too.

**Comment by njthomson** [comment]
@SkepticalFall - check the preferred commander name in settings. If a name is chosen, change it to any/no-preference.

**Comment by njthomson** [comment]
@SkepticalFall - is this still giving you any troubles?

**Comment by SkepticalFall** [comment]
@njthomson Nope, been working perfectly, thank you.

**Comment by njthomson** [comment]
Excellent - thank you for confirming.
