### ISSUE TITLE
Small pedantic issues

### ISSUE THREAD

**Issue by Vic502** [njthomson/SrvSurvey#104]
I'm liking the new update.  Good job, thanks.

I've come across two small issues:

1:  The layout of the reset and "other" button in the main window, as seen in the attached screenshot, is off.
![image](https://github.com/njthomson/SrvSurvey/assets/25501738/3dd95159-d265-4293-933a-7604f4fe441a)

2:  A pedantic issue, but kelvin units are not measured in degrees, so the degrees symbol (°) is incorrect, like on the new info panel when approaching a planet/moon.  Reference: https://www.nist.gov/si-redefinition/kelvin-introduction#:~:text=The%20kelvin%20unit%20is%20not,a%20temperature%20of%204.2%20kelvins.%E2%80%9D

**Comment by njthomson** [comment]
Thank you @Vic502, these are both worthy issues that should be fixed.

**Comment by njthomson** [comment]
I am curious, do you have large fonts or high-dpi scaling enabled on your PC?

**Comment by Vic502** [comment]
The monitor where the window is open is a 1080p with no scaling.  When I drag the SRV Survey window to the 3440X1440 monitor with 125% Windows scaling, the layout is the same, i.e. as the attached screenshot.  I've got overlay scaling set to 150%, but I don't think that applies.

**Comment by njthomson** [comment]
Are things also misaligned when on that 1080p monitor?

(You are correct that the overlay scaling does not apply to the main window)

**Comment by Vic502** [comment]
> Are things also misaligned when on that 1080p monitor?
> 
> (You are correct that the overlay scaling does not apply to the main window)

Yes, the screenshot is from the 1080p, where I always open SRV Survey.

**Comment by njthomson** [comment]
Righty ho, let me see what I can do.

**Comment by njthomson** [comment]
@Vic502 - this should be fixed as of the latest build.
