### ISSUE TITLE
Layout/scaling issue with Flight Warning window

### ISSUE THREAD

**Issue by Vic502** [njthomson/SrvSurvey#105]
The Flight Warning window (for high gravity warnings) does not scale correctly, and thus is not centered.  See attached screenshot.  The overlay scaling is set to 150% on a 3440x1440 monitor.  The height is not the issue. I managed to move it down via the plotters.json settings file.  The slightly opaque background rectangle does seem to be positioned correctly, but the red box with the warning text, not.
![Screenshot 2024-05-26 175208](https://github.com/njthomson/SrvSurvey/assets/25501738/91c3bea8-9706-4871-a7ba-35fa0be81f81)

**Comment by njthomson** [comment]
Thank you @Vic502 - your screenshot also shows another potential bug...

If body has only one bio signal, which you have scanned, there should be no ambiguity about the value. Meaning: the total for the body in the new overlay should be a single number, not "<min> ~ <max>"

**Comment by Vic502** [comment]
> Thank you @Vic502 - your screenshot also shows another potential bug...
> 
> If body `A2` has only one bio signal, which you have scanned, there should be no ambiguity about the value. Meaning: the total for the body in the new overlay should be a single number, not "`min` ~ `max`"

Oh yes, I just submitted that issue separately.

**Comment by njthomson** [comment]
@Vic502 - this should be fixed with build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.33
