### ISSUE TITLE
Feedback on the new bio status window.

### ISSUE THREAD

**Issue by Vic502** [njthomson/SrvSurvey#106]
Firstly, I like the new strikethrough effect on finished scans, it makes it a lot clearer on what is done.

The Rewards issue:  When scanning a body with 1 bio signature, and 2 possible options, the Rewards indicated is not updated correctly.  

E.g.:  I entered a system and did an FSS.  Elite Observatory BioInsights reported 2 possible signatures and indicated possible rewards of ~1-19 mil.  At this stage (before reaching the body to do a DSS) SRV Survey had no data on the body's bio signatures and only indicated that it had 1 bio signature with a "?".  

After the DSS, when the 1 bio signature was known, the Rewards section in the Bio Status window updated and indicated the "unknown" range of 1-19 mil (see screenshot below), the same as BioInsights had initially reported.  At this stage (after the DSS), BioInsights had correctly updated with the rewards for the 1 known signature.
![Screenshot 2024-05-26 185719](https://github.com/njthomson/SrvSurvey/assets/25501738/e669108b-4cb9-4461-af0c-c91b3815a651)

After landing and finishing the scan and three samples of the signature, the Rewards section had updated to the FF bonus, but still included the "unknown" range for the 2 initial possibilities. (See screenshot).
![Screenshot 2024-05-26 190225](https://github.com/njthomson/SrvSurvey/assets/25501738/312d72f5-ef44-4ec5-a92b-c7184924a688)

**Comment by njthomson** [comment]
When that overlay shows `?` in a box - there's a mew button on the main window "bio summary" that will show the list of what species it thinks is on each body - similar to BioInsights.

The prediction logic needs much tuning, hence it over-predicts. I haven't decided how to represent that long list of potentials in the small space of an overlay. Hence it just has `?` in a box for now.

**Comment by njthomson** [comment]
@Vic502 could you share a picture of the body info overlay? That might help reveal why BioInsights ruled out Stratum Tectonicas where I did not.

**Comment by njthomson** [comment]
And, when you saw those `?` ... was there a credit range next to it?

**Comment by Vic502** [comment]
> And, when you saw those `?` ... was there a credit range next to it?

No range.

**Comment by Vic502** [comment]
> @Vic502 could you share a picture of the body info overlay? That might help reveal why BioInsights ruled out Stratum Tectonicas where I did not.

Sure, let me jump back there quickly.  Not 100% which window you want.

**Comment by njthomson** [comment]
> > @Vic502 could you share a picture of the body info overlay? That might help reveal why BioInsights ruled out Stratum Tectonicas where I did not.
> 
> Sure, let me jump back there quickly. Not 100% which window you want.

The new one with Atmosphere, pressure, materials, etc.

Tarhetting the body in the system map should bring it up.

**Comment by njthomson** [comment]
> > And, when you saw those `?` ... was there a credit range next to it?
> 
> No range.

This part should be fixed in the most recent build. I need to do something similar at the time of the 3rd and final scan.

**Comment by Vic502** [comment]
![image](https://github.com/njthomson/SrvSurvey/assets/25501738/6934acd6-6ece-4693-bdd5-66b4f383ca77)
Targeting the body doesn't show it.

**Comment by Vic502** [comment]
![image](https://github.com/njthomson/SrvSurvey/assets/25501738/7c4fbeb7-1844-44a1-91ff-298eb2469e39)

**Comment by njthomson** [comment]
> ![image](https://private-user-images.githubusercontent.com/25501738/333900973-6934acd6-6ece-4693-bdd5-66b4f383ca77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDc3MjUsIm5iZiI6MTcxNjc0NzQyNSwicGF0aCI6Ii8yNTUwMTczOC8zMzM5MDA5NzMtNjkzNGFjZDYtNmVjZS00NjkzLWJkZDUtNjZiNGYzODNjYTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE4MTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhN2JkMjI4YzA4NjI4MGYyMGY3ZjI4OWMyZDk5N2JhOTgyM2U4NjkxZWI5NThiYjAwZDk1YjY5NTNjMWU0ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1EwZGdYQHszLZim6EGN3QFT2Qe2mZq6IzYAefFmidZc) Targeting the body doesn't show it. Flying closer.

There's selecting it, and also choosing it as the target destination. (When it gets a blue "pin" on top).
Journal files only reveal when it is your destination.

**Comment by Vic502** [comment]
Now I don't see anything wrong after returning to this body.

**Comment by njthomson** [comment]
> Now I don't see anything wrong after returning to this body.

This is expected. The bug is that certain calculations do not occur on that 3rd and final scan.
They do occur when re-entering a system.

**Comment by Vic502** [comment]
Hope this helps.  Let me know if I can test anything else specifically.

**Comment by njthomson** [comment]
> Hope this helps. Let me know if I can test anything else specifically.

Noting where BioInsights rules out some species but SrvSurvey does not will be helpful. It will take a while to discern all the factors controlling the species.

**Comment by njthomson** [comment]
The main issue reported here should be fixed as of this build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.33

I saw see the reward not updating when expected for other reasons, will keep this bug open until those are fixed.
