### ISSUE TITLE
SRVSurvey Canonn download

### ISSUE THREAD

**Issue by Prinz-von-Oelen** [njthomson/SrvSurvey#112]
Hello, first of all: thanks for the SRV Survey app! Its awesome!

My current question is, the windows with the canonn downloads of the scan worth of bio signals does rarely show. Am I missing something? what triggers the window?

**Comment by njthomson** [comment]
@Prinz-von-Oelen - did you mean the really new window with screenshots from Canonn? This appears when you scan something, but I'm going to make it easier than that.

Or did you mean the overlay on the left with prior scan locations? This overlay appears any time someone uploading data has been there before.

**Comment by Prinz-von-Oelen** [comment]
Hi - sorry for the late response, got alot going around these days.
But thank you, that clarifies it already: I am deep in the wilds scanning some space-cabbage and it seems that I stumbled across the master works of someone else. That way I saw the new window pop up. Was somehow handy since it showed everything I needed to know.

Other question: on the top is the overlay that shows the estimated worth of the plants. Is there an opt-out option to see just the raw value and not the ff-bonus applied?

**Comment by njthomson** [comment]
You can un-check the first foot fall box on the main window, or send an in-game message `.ff` to make it not apply the 5x bonus.

I will add a new setting to make this optional.

**Comment by Prinz-von-Oelen** [comment]
Thank you =)

**Comment by njthomson** [comment]
Just curious, are you using the GitHub build or from the App store?

**Comment by Prinz-von-Oelen** [comment]
From the app store. It was stated that it would be updated automatically. thats handy.

**Comment by njthomson** [comment]
You'll like what's coming up soon then. This new overlay predicts species, shows their values and uses a icons so we can assess the whole value of a body without squinting at numbers.


![image-19](https://github.com/user-attachments/assets/159d7517-d289-4615-b2b6-be34451791b9)

**Comment by Prinz-von-Oelen** [comment]
WOW ! ! ! You are a mind reader - didnt dare to ask if a prediction would be possible! I use the google docs list from the webs XD

**Comment by njthomson** [comment]
There's a new overlay when FSS'ing too
![image-11](https://github.com/user-attachments/assets/b5a769e4-385f-4eac-9ce1-9584d4ce72c5)

Consider the GitHub build :)

**Comment by Prinz-von-Oelen** [comment]
Gloriuos! Thank you! When will it be available?

**Comment by njthomson** [comment]
I'm hoping within 2 weeks.

**Comment by Prinz-von-Oelen** [comment]
Thanks alot =)

**Comment by njthomson** [comment]
@Prinz-von-Oelen - at long last, the Windows app store version has been updated.

**Comment by Prinz-von-Oelen** [comment]
Great news! I am a bit busy these days and dont know when I will be able to fire ED up. But I will give it a try as soon as possible!

**Comment by Hansen82** [comment]
Would it be possible to make SrvSurvey upload data to Canonn when for example we discover new fauna?
