### ISSUE TITLE
Bio scanning constantly shows unclaimed rewards

### ISSUE THREAD

**Issue by lanzz** [njthomson/SrvSurvey#115]
SrvSurvey constantly shows 460M / 25 organisms of unclaimed bio scanning rewards. I tried clearing the unclaimed rewards in settings, but next time I accumulated and sold bio data, I was again left with 460M of unclaimed rewards (I'm not sure if the number of organisms was the same last time and this time, but the amount was about 460M in both occurrences). It's not stuck, it's showing extra scans as I collect them, but after I sell everything there's always about 460M left over, while Vista shows nothing more to sell.

**Comment by njthomson** [comment]
Thank you @lanzz for reporting this. A few questions for you:

A) did you install from GitHub or the Microsoft store?

B) what version are you using? (It will say in settings)

C) do you use multiple cmdr accounts?

Thanks!

**Comment by lanzz** [comment]
Apologies, I was apparently not running latest release 😳
