### ISSUE TITLE
Unable to start just says to report this

### ISSUE THREAD

**Issue by asanovic7** [njthomson/SrvSurvey#133]
### What happened?
I run setup or exe file I get this:
System.nullreferenceException: object reference not set a instance to an object. at srvsurvey..ctor() in ../srvsurvey/main.cs:line 36
at srvsurvey.program(string[]args) in ../srvsurvey/program.cs:line 85

### Version

2.02.7

### Exception message

System.nullreferenceException: object reference not set a instance to an object. at srvsurvey..ctor() in ../srvsurvey/main.cs:line 36
at srvsurvey.program(string[]args) in ../srvsurvey/program.cs:line 85

### Exception stack

System.nullreferenceException: object reference not set a instance to an object. at srvsurvey..ctor() in ../srvsurvey/main.cs:line 36
at srvsurvey.program(string[]args) in ../srvsurvey/program.cs:line 85

**Comment by asanovic7** [comment]
Whatever I start exe or setup it says this. Tried windows version also. Tx

**Comment by asanovic7** [comment]
Hey hey I managed to fix the bug. If anyone has the same issue, I deleted everything in appdata roaming srvsurvey folder and restarted app. It started and hopefully working.

**Comment by njthomson** [comment]
I would not recommend deleting that while folder. Just `settings.json` at first. Glad you are unblocked though.

**Comment by asanovic7** [comment]
as far as I am seeing it is working ok. I had two additional folders besides mai one. about the app - main thing for me is exo and explo info right away when you enter into system, especially known, which is such a big quality of life thing. cheers :)
