### ISSUE TITLE
Download of 2.02.27 is being caught by Windows Defender as a virus

### ISSUE THREAD

**Issue by DawnTreader** [njthomson/SrvSurvey#137]
![image](https://github.com/user-attachments/assets/2d2abc40-30e0-48a1-a872-6ca293ee25dc)
Not sure what else to say.

**Comment by njthomson** [comment]
@DawnTreader - that is unusual, does it say the same for the .zip from here?
https://github.com/njthomson/SrvSurvey/actions/runs/11529602520

**Comment by NI6H70WL** [comment]
Same, warning of a trojan.

Trojan:Script/Wacatac.B!ml

**Comment by NI6H70WL** [comment]
> @DawnTreader - that is unusual, does it say the same for the .zip from here? https://github.com/njthomson/SrvSurvey/actions/runs/11529602520

![image](https://github.com/user-attachments/assets/3caeaaae-00c1-4804-8525-a9dd18757e79)
Same again.
Older version works.

**Comment by njthomson** [comment]
The older version you had was ... `2.0.2.19` ?

**Comment by NI6H70WL** [comment]
> The older version you had was ... `2.0.2.19` ?

I had no version before, I tried to download version 2.0.2.19, without a problem.

**Comment by njthomson** [comment]
Does this one fair any better?
https://github.com/njthomson/SrvSurvey/actions/runs/11536412743

These warnings surprise me as the .zip files are produced by a GitHub build directly. The interesting recent changes are that I'm starting to support more languages than before.

**Comment by NI6H70WL** [comment]
![image](https://github.com/user-attachments/assets/4640457c-d977-4430-b91a-e7bd5d706594)


Worked 👍 

I have to say, I was surprised to get the trojan warning. Iwas satisfied with the older version too. ;-)

**Comment by njthomson** [comment]
Very odd. The same system produced all the files. Glad the later one is not raising any flags though.

**Comment by njthomson** [comment]
I'm going to close this out, but please don't hesitate to give me shout if you see further issues.
