### ISSUE TITLE
Request: movable overlays

### ISSUE THREAD

**Issue by njthomson** [njthomson/SrvSurvey#14]
Can we have overlay windows outside of the game window?

Aka: can they be movable to an arbitrary location?

Requested by: Randodom

**Comment by DawnTreader** [comment]
Agree. Talked with dev on discord, he said he might whip something up.

**Comment by njthomson** [comment]
This is implemented as of build `1.1.0.13`: https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.13

See details on the wiki: https://github.com/njthomson/SrvSurvey/wiki/Custom-overlay-positioning
