### ISSUE TITLE
Add ability to move overlays with mouse and save positions.

### ISSUE THREAD

**Issue by Silent369** [njthomson/SrvSurvey#141]
It would be very helpful to be able to move overlays with the mouse to position them where we would like on screen. Srv Survey would then save those positions.

**Comment by njthomson** [comment]
That would be nice indeed. It's certainly viable but will need some effort. As each overlay is pinned to an edge or corner of the game - there needs to be a way to adjust that too.

I'm thinking a little popup window to provide more options, that appears after pressing a particular key sequence. I will ponder this and see what I can do.

**Comment by Silent369** [comment]
Even if it is a popup that allows us to adjust on screen coordinates, since the overlay positions are quite agreeable for the most part. My issue is that on my current screen resolution, 2560 x 1440, the two left panels slightly overlap. It would therefore be nice to be able to adjust their respective coordinate positions and save that.

**Comment by njthomson** [comment]
@Silent369 - just curious, were you familiar with this?
https://github.com/njthomson/SrvSurvey/wiki/Custom-overlay-positioning

Either way, there's a new button in settings now...
![image](https://github.com/user-attachments/assets/3e5adf59-389c-4c8e-a6b2-6079b1338dd7)

... that pop's this dialog where you can make changes in real time:
![image](https://github.com/user-attachments/assets/a0e78ea6-b92f-4260-a5b4-5999e0aba2a6)

https://github.com/njthomson/SrvSurvey/releases/tag/2.0.2.40

**Comment by Silent369** [comment]
My apologies, i was not aware of that!

**Comment by njthomson** [comment]
With this build, individual opacities can now be set, enjoy:
https://github.com/njthomson/SrvSurvey/releases/tag/2.0.2.41
