### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by OPlurker1005** [njthomson/SrvSurvey#142]
### What happened?

I had just updated from 2.0.2.31 to 2.0.2.32 because it also crashed on startup, but I forgot to get a screenshot of the crash before I closed it. I think it was the same error message.

### Version

2.0.2.32

### Exception message

An unexpected error occurred. Please report the following on Https://github.com/njthonson/SrvSurvey/issues:

### Exception stack

System.OverflowException: Arithmetic operation resulted in an overflow.
at
System.Diagnostics.NtProcessInfoHelper.GetProcessInfos(ReadOnlySpan'1 data, Nullable'1 processIdFilter, String processNameFilter)
at
System.Diagnostics.NtProcessInfoHelper.GetProcessInfos(Nullable'1 processIdFilter, String processNameFilter)
at
System.Diagnostics.ProcessManager.GetProcessInfos(String processNameFilter, String machineName)
at SrvSurvey.Program.Main(String[] args)

### Relevant log output
![SrvSurveyCrash](https://github.com/user-attachments/assets/d464ebcd-6ac7-477d-80f2-f9109be51deb)

_No response_

**Comment by OPlurker1005** [comment]
Just tried to install .31, then .27, then .19.  Getting the same error message on statup.  So I am guessing the error started in 2.0.2.31, when I updated from 2.0.2.27 to 2.0.2.31. Never started it after updating and got back to a it day later.

I started 2.0.2.31 and it crashed. Checked for an update and now we are here.

**Comment by OPlurker1005** [comment]
[srvs-20241101_235902.txt](https://github.com/user-attachments/files/17605703/srvs-20241101_235902.txt)
[srvs-20241102_000100.txt](https://github.com/user-attachments/files/17605704/srvs-20241102_000100.txt)
[srvs-20241102_000247.txt](https://github.com/user-attachments/files/17605705/srvs-20241102_000247.txt)
[srvs-20241102_000436.txt](https://github.com/user-attachments/files/17605706/srvs-20241102_000436.txt)
[srvs-20241102_004849.txt](https://github.com/user-attachments/files/17605707/srvs-20241102_004849.txt)

**Comment by njthomson** [comment]
Thank you for reporting this, and I am glad a reboot seemed to do the trick. Give me a shout if you experience more troubles with SrvSurvey.
