### ISSUE TITLE
App layout not scaling to Windows desktop scaling

### ISSUE THREAD

**Issue by Vic502** [njthomson/SrvSurvey#145]
It would be nice if the app scaled according to the Windows scaling settings.  As it stands, some info is not visible with 125% scaling on a 3440X1440 resolution.   See attached screenshots.

![Screenshot 2024-11-08 084021](https://github.com/user-attachments/assets/1f73ee7c-ae17-4e92-bbd7-82b0df728f08)
![Screenshot 2024-11-08 084032](https://github.com/user-attachments/assets/4cfa1a39-9084-4f3d-b33b-8cf6805fd585)

**Comment by Vic502** [comment]
The overlay scaling in-game is working 100%, this is only for the Windows application.

**Comment by njthomson** [comment]
Thank you @Vic502 for reporting this, they will be fixed in the next build.

**Comment by njthomson** [comment]
Give this a whirl:
https://github.com/njthomson/SrvSurvey/releases/tag/2.0.2.43

**Comment by Vic502** [comment]
Thanks man!  Works 100% now. Cheers!
