### ISSUE TITLE
Not really a suggestion - possibly a bug?

### ISSUE THREAD

**Issue by Xariss00** [njthomson/SrvSurvey#154]
Unless I missed it somewhere in the documentation, there appears to be a small bug in the Next System Summary overlay.  When jumping into a system with a White Dwarf or Neutron as it's primary, the summary overlay does not display a star class at all.

Again, thanks!  SRV Survey has replaced a number of third-party tools for me.  It's amazing!

**Comment by njthomson** [comment]
Thank you @Xariss00 for reporting this (and thank you for your kind words)

Which build are you using? The star class is supposed to be shown in the top right corner.

**Comment by Xariss00** [comment]
2.0.2.42

All other star classes (so far) show in the top right of the System Summary overlay - just not neutrons or white dwarfs (again, so far).

**Comment by njthomson** [comment]
Very curious ... I should have that fixed in the next build.

**Comment by njthomson** [comment]
@Xariss00 - could you share the whole SrvSurvey log file when this next happens?

I cannot repro the same :/
![image](https://github.com/user-attachments/assets/c5b398d6-2b37-4842-b282-d285c79dd0dc)

And/or - do you have large-fonts or high-dpi enabled on your system?

**Comment by Xariss00** [comment]
Haven't had time to log in and grab a log, however:
1)  Yes - I play on a laptop and keep my desktop at 125% scale.
2)  I updated to build 2.02.55 today and it seems to have resolved the issue, at least with White Dwarfs.  I'm going to mark this as closed, but will keep an eye out in case any of the other non-sequence/unusual star classes cause issues.

Thanks for the quick fix!
CMDR Xariss00
