### ISSUE TITLE
custom overlay settings not saving / being read

### ISSUE THREAD

**Issue by SgtEpsilon** [njthomson/SrvSurvey#155]
I'm trying to save custom opacity for a couple of the overlays to hide them both with the built in custom overlay settings and manually editing the files and neither of the opacity settings are being read when i save, all other settings work fine.

``` "PlotBioStatus": "center:0, top:8",
  "PlotBioSystem": "left:-8, bottom:-4",
  "PlotBodyInfo": "left:8, top:8",
  "PlotFlightWarning": "center:0, top:90",
  "PlotFSS": "center:0, top:8, opacity:0",
  "PlotFSSInfo": "left:8, top:8",
  "PlotGalMap": "left:8, top:8, opacity:0",
  "PlotGrounded": "right:0, middle:-200",
  "PlotGuardians": "left:8, middle:0",
  "PlotGuardianStatus": "center:0, top:8",
  "PlotGuardianSystem": "left:10, top:8",
  "PlotHumanSite": "left:8, middle:0",
  "PlotJumpInfo": "center:0, top:8",
  "PlotMassacre": "right:8, top:8",
  "PlotPriorScans": "left:0, top:260",
  "PlotPulse": "left:8, bottom:8",
  "PlotRamTah": "right:8, middle:0",
  "PlotSphericalSearch": "right:8, top:8",
  "PlotSysStatus": "left:8, bottom:44, 0.65",
  "PlotTrackTarget": "center:480, top:8"
```

**Comment by njthomson** [comment]
@SgtEpsilon - try without including `opacity:` - the format you have for `PlotSysStatus` looks correct, but `PlotGalMap` and `PlotFSS` do not.

I wouldn't generally recommend using opacity to hide certain overlays, although it certainly works in that regard. These two settings will hide those:
![image](https://github.com/user-attachments/assets/23d6c077-fa00-4457-9f16-f6b010e2b36f)

**Comment by njthomson** [comment]
@SgtEpsilon - is this still giving you any trouble?

**Comment by SgtEpsilon** [comment]
No, sorry i never replied sooner i got a bit busy and completely forgot

**Comment by njthomson** [comment]
I'm going to close this out, but do not hesitate to re-activate or give me a shout if it gives you any more grief.
