### ISSUE TITLE
Tool is unusable

### ISSUE THREAD

**Issue by h5vx** [njthomson/SrvSurvey#20]
**Describe the bug**
I tried to use this tool as a exobiology helper in E.D: Odyssey that is launched from Steam on Win 10
- Installed it through setup.exe
- Launched Srv Survey through installed application shortcut
- Got blank screen for few seconds
- Hear some panel switching sounds from game window (which is still in background)
- Nothing happens nor in the game, nor on the desktop. Nothing in tray, no main window, no overlays in game
- Also tried to launch Srv Survey first (still no main window), then the game. Nothing happens either

So I doesn't know how to use that tool. I tried hard reading documentation, got no clues from it.

Also, it seems that tool allows to run as second process. I suspect this can cause problems, so before restarting the tool I manually kill it's old process

**Version:**
- 1.0.9.19

**Logs:**
Have no clue where they are stored

**Comment by brammmers** [comment]
Things to check: 

That Elite is configured for "Windowed" or "Borderless Window" mode - NOT fullscreen.
Try the latest build (1.0.9.33, as that has had a lot of fixes added) from here: https://github.com/njthomson/SrvSurvey/actions/runs/7217779357/artifacts/1116466989

**Comment by njthomson** [comment]
@h5vx - thank you for reporting this issue. There were some bugs found in the start-up sequence with that build.

I will update the release shortly once a build is ready.

**Comment by njthomson** [comment]
@h5vx - the build is ready, please try again using build `1.0.9.37`

**Comment by njthomson** [comment]
@h5vx - please try again using build `1.0.9.59` - see [https://github.com/njthomson/SrvSurvey/releases/tag/1.0.9.59](https://github.com/njthomson/SrvSurvey/releases/tag/1.0.9.59)

**Comment by njthomson** [comment]
@h5vx I'm closing this issue, but please do let me know either way if it is fixed or not.
