### ISSUE TITLE
Tool uses hard coded location for saved games, causes it to crash when saved games are at a different drive

### ISSUE THREAD

**Issue by cyberbofh** [njthomson/SrvSurvey#22]
Looks like the tool is hard coded to look at the C-drive for elite saved games
When saved games are on a different drive, tool crashes

getting error:
ArgumentException:The directory name 'C:\Users\<username>\Saved Games\Frontier Developments\Elite Dangerous\' does not exist. (Parameter 'path')
(replaced username with <username>)

**Expected behavior**
probably best if tool uses system environment variable %username%, instead of "C:\users\<username>"

**Comment by njthomson** [comment]
Thank you @cyberbofh for reporting this. There is a setting to change the watched folder, but that won't help if it crashes before you can click on settings.

As a manual work-around, you can hand-edit `%appdata%\SrvSurvey\SrvSurvey\1.1.0.0\settings.json` with the correct folder to watch.

**Comment by njthomson** [comment]
@cyberbofh - an you check if `%userprofile%` on your system points to the C or D drive?

Checking the code, it already uses an environment variable to get the user's default folder.

**Comment by cyberbofh** [comment]
@njthomson 

TY for your quick reply

I checked and..
BOTH %username% and %userprofile% point to the same location

The confusing part is that when I try these - they'll work in my windows explorer - they point to the right location of my \Saved Games\

"%username%\Saved Games\" >> "otherdrive:\<folder>\<username>\Saved Games"
"%userprofile%\Saved Games\" >> "otherdrive:\<folder>\<username>\Saved Games"

but the app, somehow, turns it into
"C:\Users\<username>\Saved Games\"

FYI
I MOVEd the location of "\Saved Games\" to a different drive, but left the location of the user profile at the original location (C-drive)

Possible solution?
I am using several tools for ED - EDMarketConnector; Elite Dangerous Odyssey Materials Helper; ODMissionStacker - and they all have an option to point out to an alternate location of the journal folder

**Comment by njthomson** [comment]
@cyberbofh - could you share the callstack of the error? It should be visible in the "Oops" dialog, albeit it in small text.

**Comment by njthomson** [comment]
@cyberbofh - I did not realize previously. were you were using the build from the Microsoft App Store? If so ... I have a fix pending for this issue.

**Comment by njthomson** [comment]
@cyberbofh - a fix has been deployed to the Microsoft App store. Please let me know if it gives you any further grief.
