### ISSUE TITLE
request: show feasable bio species on overlay

### ISSUE THREAD

**Issue by bbbkada** [njthomson/SrvSurvey#24]
Really preciate this tool.
I would love to see what I can expect from biosignals found without checking atmosphere, temperture, bodymass and compare to ed-dsn webpage. That would speed up exploration alot.
I'm talking about this site:
https://ed-dsn.net/en/conditions-of-emergence-of-exobiological-species-on-planets-a-atmosphere-fine/

Must be possible to calculate this in your tool ?

Thanks for a great new tool.

**Comment by njthomson** [comment]
That should be viable, I've seen it done in other tools. Not sure how much work it would be.

The real question is how best to display such information? I prefer to keep the overlays minimal and this could be a lot of text to show.

Is it actually the species/variants you want to see or the potential credits to be earned?

 - nick
________________________________
From: bbbkada ***@***.***>
Sent: Sunday, December 31, 2023 6:16:31 PM
To: njthomson/SrvSurvey ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [njthomson/SrvSurvey] request: show feasable bio species on overlay (Issue #24)


Really preciate this tool.
I would love to see what I can expect from biosignals found without checking atmosphere, temperture, bodymass and compare to ed-dsn webpage. That would speed up exploration alot.
I'm talking about this site:
https://ed-dsn.net/en/conditions-of-emergence-of-exobiological-species-on-planets-a-atmosphere-fine/

Must be possible to calculate this in your tool ?

Thanks for a great new tool.

**Comment by bbbkada** [comment]
Preferably like EDMC Canonn plugin show them after you scanned, ($19) Stratum Tectonicas.
Thats an established currency for most people, I think ?

**Comment by njthomson** [comment]
Work has started on this feature.

**Comment by njthomson** [comment]
@bbbkada - this has been implemented.
