### ISSUE TITLE
Exception "Why no lastCargoEntry?" at 1/5/2024 19:51:45 -05:00

### ISSUE THREAD

**Issue by msteele999** [njthomson/SrvSurvey#30]
### What happened?

Closed game after a 1 hour mining session

### Version

1.0.0.0+e7a842ffaa2afeffa4d3be794dff444b015ead69

### Exception message

Why no lastCargoEntry?

### Exception stack

   at SrvSurvey.game.Game.initCargoData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

### Relevant log output

```shell
19:49:59: Mode change Flying => Docked
19:50:05: Mode change Docked => InternalPanel
19:50:26: Mode change InternalPanel => Docked
19:50:27: Mode change Docked => StationServices
19:50:47: Mode change StationServices => Docked
19:50:54: Mode change Docked => Offline
19:50:57: EliteDangerous process died?!
19:50:57: Main.removeGame, has old game: True
19:50:57: Program.CloseAllPlotters
19:50:57: Program.Closing plotter: PlotPulse
```

**Comment by njthomson** [comment]
@msteele999 - a fix is available, please try build `1.1.0.2` - https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.2
