### ISSUE TITLE
request: overlay scalable

### ISSUE THREAD

**Issue by DeepstarOne** [njthomson/SrvSurvey#32]
Hi,

a great tool but currently it is not usable for me because the overlays are too small on a 4k monitor (or at least I haven't found a way to change this up to now). Is there a possibility to scale the overlay windows (e.g. 200 %, 400 %, ...) or could this be implemented?

Thanks!

**Comment by njthomson** [comment]
Hi @DeepstarOne - alas, there is no scaling mechanism built in today.

I am confident a scaling mechanism could be made, but I suspect it would require quite a bit of time and a lot of testing.

I will look into what it might take to double everything, hence 200% or 400% might be viable, but it I cannot guarantee anything at this time.

**Comment by msteele999** [comment]
I would also like this feature - I am running a 2K monitor

**Comment by Vic502** [comment]
Yes, also running 2k and would love a larger font, please.  Otherwise, great tool.  Cheers!

**Comment by AuerXX** [comment]
screen resolution of 3840x1080, ability to increase font size would be great.

**Comment by njthomson** [comment]
Given the continued and consistent enquiries on this front - I will start on this soon, after releasing Guardian sites updates to the Microsoft App store.

**Comment by njthomson** [comment]
@DeepstarOne @msteele999 @Vic502 @AuerXX  - work has started for this. I anticipate having the exploration overlays ready before long. The Guardian ones will take longer.

**Comment by njthomson** [comment]
@DeepstarOne @msteele999 @Vic502 @AuerXX - please try this latest build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.1.3

There's a new setting now to match the OS scaling factor, or force 1x 1.5x or 2x scaling independently.
![image](https://github.com/njthomson/SrvSurvey/assets/3903773/7f27f86e-e2b8-4724-8f28-ef2e6f7ec9fc)

**Comment by njthomson** [comment]
@DeepstarOne @msteele999 @Vic502 @AuerXX - this is ready:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.1.4

**Comment by DeepstarOne** [comment]
![2024-03-23 13_36_05-Greenshot](https://github.com/njthomson/SrvSurvey/assets/25210660/ad04e4ef-0db2-410e-9b92-fee310bfbe09)
Seems to work very well on a 4k display with max. scaling factor (200%). Thanks for this feature! :-)

**Comment by njthomson** [comment]
@DeepstarOne - do you feel there's a need to go higher? Or have 25% increments?

**Comment by DeepstarOne** [comment]
Probably 250% would be perfect for me. If the programming effort isn't too high, users could adjust the overlay exactly to their needs with 25% increments.

**Comment by njthomson** [comment]
At this point it's trivial to add more levels :)

I'll add those.

**Comment by Vic502** [comment]
Whoop!  Downloading now, to try this.  Cheers mate!

**Comment by Vic502** [comment]
Yeah, works like a charm. My bad eyes thank you!  Regarding increments, the scale currently matches my OS @ 125%, which is much better than 100%, but could be a tad larger, although 150% is too large.  So maybe 10% increments?  Maybe I'm just nitpicking.  Cheers anyway, mate.  I really appreciate this change.

**Comment by msteele999** [comment]
Just catching up on emails and will be trying it shortly - thanks for
making this happen!

**Comment by msteele999** [comment]
Works fantastic!

I agree that 150% is a bit too large on my 2K monitor. 10 or 25% increments
would be great

**Comment by njthomson** [comment]
Alrighty, give this build a try:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.1.5

![image](https://github.com/njthomson/SrvSurvey/assets/3903773/753d279d-7d02-4112-b2b1-3ec26617fffc)

**Comment by msteele999** [comment]
That works perfectly!

**Comment by AuerXX** [comment]
Very good! Thanks!

**Comment by njthomson** [comment]
This feature is now available in the Microsoft App store - thank you all for your patience and testing efforts.
