### ISSUE TITLE
ArgumentNullException "Value cannot be null. (Parameter 'values')" at 1/6/2024 11:40:36 -05:00

### ISSUE THREAD

**Issue by msteele999** [njthomson/SrvSurvey#33]
### What happened?

Closed Elite - this is after updating to patched version

### Version

1.1.0.2

### Exception message

Value cannot be null. (Parameter 'values')

### Exception stack

   at System.String.JoinCore[T](ReadOnlySpan`1 separator, IEnumerable`1 values)
   at System.String.Join[T](String separator, IEnumerable`1 values)
   at SrvSurvey.game.Game.initCargoData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

### Relevant log output

```shell
08:04:37: Mode change Flying => InternalPanel
08:04:49: Mode change InternalPanel => Flying
08:05:02: Mode change Flying => ExternalPanel
08:05:06: Mode change ExternalPanel => Flying
08:05:25: Mode change Flying => SuperCruising
08:05:26: Mode change SuperCruising => ExternalPanel
08:05:28: Mode change ExternalPanel => SuperCruising
08:05:56: Mode change SuperCruising => Flying
08:06:00: Mode change Flying => ExternalPanel
08:06:07: Mode change ExternalPanel => Flying
08:06:59: Mode change Flying => Docked
08:07:04: Mode change Docked => InternalPanel
08:07:23: Mode change InternalPanel => Docked
08:07:25: Mode change Docked => StationServices
08:08:17: Mode change StationServices => Docked
08:08:25: Mode change Docked => Offline
08:08:27: EliteDangerous process died?!
08:08:27: Main.removeGame, has old game: True
08:08:27: Program.CloseAllPlotters
08:08:27: Program.Closing plotter: PlotPulse
```

**Comment by njthomson** [comment]
Thanks @msteele999 - this will be fixed in the next build.

**Comment by njthomson** [comment]
@msteele999 - this has been fixed as of build: https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.6
