### ISSUE TITLE
Exception "Why no lastCargoEntry?" at 07/01/2024 12:51:02 +00:00

### ISSUE THREAD

**Issue by brammmers** [njthomson/SrvSurvey#35]
### What happened?

don't know, ooops window was buried under others :)

### Version

1.0.0.0+e7a842ffaa2afeffa4d3be794dff444b015ead69 (build 89 actually)

### Exception message

Why no lastCargoEntry?

### Exception stack

   at SrvSurvey.game.Game.initCargoData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

### Relevant log output

```shell
12:41:25: Mode change Docked => Flying
12:41:38: Mode change Flying => GalaxyMap
12:41:52: Mode change GalaxyMap => Flying
12:41:53: Mode change Flying => GalaxyMap
12:42:19: Mode change GalaxyMap => Flying
12:43:29: Mode change Flying => SuperCruising
12:43:30: Mode change SuperCruising => InternalPanel
12:43:34: Mode change InternalPanel => SuperCruising
12:49:14: Mode change SuperCruising => SystemMap
12:49:20: Mode change SystemMap => SuperCruising
```

**Comment by njthomson** [comment]
@brammmers - can you try this build: https://github.com/njthomson/SrvSurvey/actions/runs/7437160359

**Comment by brammmers** [comment]
build 1.1.0.5, installed and opened it (while ED was already running):
IOException:The process cannot access the file 'C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240107_222902.txt' because it is being used by another process.

   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at SrvSurvey.game.Game.log(Object msg)
   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<>c__DisplayClass11_0.<Main_Load_Async>b__1()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

Complete logs entry:

22:29:02: SrvSurvey version: 1.1.0.5
22:29:02: New log file: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240107_222902.txt
22:29:02: dataFolder: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0
22:29:03: Removing old log file: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20231229_205450.txt
22:29:03: Loaded settings: {
  "preferredCommander": "",
  "lastCommander": "BRAMMMERS",
  "lastFid": "F10288402",
  "watchedJournalFolder": "C:\\Users\\jason\\Saved Games\\Frontier Developments\\Elite Dangerous\\",
  "hideJournalWriteTimer": false,
  "targetLatLong": {
    "lat": 63.102,
    "long": 117.1199
  },
  "targetLatLongActive": true,
  "autoShowBioSummary": true,
  "autoShowBioPlot": true,
  "autoShowPlotFSS": false,
  "autoShowGuardianSummary": true,
  "autoShowRamTah": true,
  "autoShowPlotSysStatus": true,
  "skipGasGiantDSS": true,
  "skipRingsDSS": false,
  "skipLowValueDSS": true,
  "skipLowValueAmount": 1000000,
  "autoTrackCompBioScans": true,
  "skipAnalyzedCompBioScans": true,
  "autoRemoveTrackerOnSampling": true,
  "useExternalData": false,
  "autoLoadPriorScans": true,
  "skipPriorScansLowValue": false,
  "skipPriorScansLowValueAmount": 1000000,
  "showCanonnSignalsOnRadar": true,
  "useSmallCirclesWithCanonn": true,
  "hideMyOwnCanonnSignals": true,
  "focusGameOnStart": true,
  "focusGameOnMinimize": true,
  "enableGuardianSites": true,
  "enableEarlyGuardianStructures": false,
  "disableRuinsMeasurementGrid": false,
  "disableAerialAlignmentGrid": false,
  "hidePlottersFromCombatSuits": false,
  "hideOverlaysFromMouse": true,
  "autoShowFlightWarnings": true,
  "highGravityWarningLevel": 1.0,
  "plotterOpacity": 50.0,
  "formMainLocation": "3060, 1066",
  "formLogsLocation": "0, 0, 0, 0",
  "formAllRuinsLocation": "0, 0, 0, 0",
  "formRuinsLocation": "0, 0, 0, 0",
  "formBeaconsLocation": "0, 0, 0, 0",
  "formMapEditor": "0, 0, 0, 0",
  "formRamTah": "0, 0, 0, 0",
  "mapShowNotes": true,
  "blinkTigger": 134217728,
  "blinkDuration": 3000,
  "processScreenshots": false,
  "addBannerToScreenshots": true,
  "deleteScreenshotOriginal": false,
  "useGuardianAerialScreenshotsFolder": true,
  "screenshotSourceFolder": "D:\\Users\\jason\\OneDrive\\Pictures\\Frontier Developments\\Elite Dangerous",
  "screenshotTargetFolder": "D:\\Users\\jason\\OneDrive\\Pictures\\Frontier Developments\\Elite Dangerous\\converted",
  "rotateAndTruncateAlphaAerialScreenshots": true,
  "aerialAltAlpha": 1200.0,
  "aerialAltBeta": 1550.0,
  "aerialAltGamma": 1600.0,
  "idxGuardianPlotter": 0,
  "migratedAlphaSiteHeading": false,
  "inferColor": "118, 178, 248",
  "inferTolerance": 25,
  "inferThreshold": 0.002,
  "dataFolder1100": true,
  "pubDataSettlementTemplate": 9,
  "pubDataGuardian": 9,
  "processIdx": 0
}
22:29:03: Watching folder: C:\Users\jason\Saved Games\Frontier Developments\Elite Dangerous\
22:29:03: Watching file: C:\Users\jason\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
22:29:03: isMigrationValid: True, dataFolder1100: True
22:29:03: updatePubData ...
22:29:03: Loaded 512 ruins, 30 beacons, 155 beacons
22:29:03: Using settlementTemplates.json from pubData
22:29:03: Reading settlementTemplates.json: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\settlementTemplates.json
22:29:03: SiteTemplate.Imported 13 templates
22:29:03: CodexRef init ...
22:29:03: loadCodexRef: reading codex/ref from disk
22:29:03: prepBioRef: reading bioRef from disk
22:29:03: loadOrganicRewards: reading organic rewards from disk
22:29:03: CodexRef init - complete
22:29:03: Main.newGame: has old game:False 
22:29:03: Game .ctor
22:29:03: Reading: Journal.2024-01-07T221716.01.log
22:29:03: Game.initializeFromJournal: BEGIN  (FID:), journals.Count:28
22:29:03: Loaded data from: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\F10288402-live.json
22:29:03: Changed hasLatLong: True, has nearBody: False, nearBody matches: False
22:29:03: setCurrentBody by name: Synuefe NU-M d8-37 A 1
22:29:03: setCurrentBody: No systemData - ignoring bodyName: Synuefe NU-M d8-37 A 1
22:29:03: Mode change NoFocus => MainMenu
22:29:03: Game.initSystemData: rewind to last FSDJump or CarrierJump
22:29:03: Game.initSystemData: last location: 'Synuefe NU-M d8-37' (1281871546699)
22:29:03: Reading: Journal.2024-01-07T120137.01.log
22:29:03: Game.initSystemData: found last FSDJump, to 'Synuefe NU-M d8-37' (1281871546699)
22:29:03: Loading SystemData for: 'Synuefe NU-M d8-37' (1281871546699)
22:29:03: Loaded data from: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\systems\F10288402\Synuefe NU-M d8-37_1281871546699.json
22:29:03: walkDeep: count: 2
22:29:03: Game.initSystemData: Processing 97 journal items forwards...
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:51:09)
22:29:03: Game.initSystemData: playForwards 'FSSDiscoveryScan' (07/01/2024 12:53:12)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:12)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:27)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:34)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:38)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:44)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:53)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:57)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:01)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:06)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:08)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:11)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:13)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:15)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:19)
22:29:03: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 12:55:26)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:26)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:30)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:29:03: pubDataSettlementTemplate - local: 9, remote: 9
22:29:03: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:29:03: pubDataGuardian - local: 9, remote: 9
22:29:03: updatePubData - complete
22:29:03: Exception: The process cannot access the file 'C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240107_222902.txt' because it is being used by another process.
22:29:03: Inner exception: 
22:29:03: Stack:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at SrvSurvey.game.Game.log(Object msg)
   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<>c__DisplayClass11_0.<Main_Load_Async>b__1()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
22:29:18: Opening link: (length: 45)
https://github.com/njthomson/SrvSurvey/issues

**Comment by brammmers** [comment]
A close and reopen of 1.1.0.5 seems to be ok, logs:

22:34:13: SrvSurvey version: 1.1.0.5
22:34:13: New log file: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240107_223413.txt
22:34:13: dataFolder: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0
22:34:13: Removing old log file: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20231230_071957.txt
22:34:13: Loaded settings: {
  "preferredCommander": "",
  "lastCommander": "BRAMMMERS",
  "lastFid": "F10288402",
  "watchedJournalFolder": "C:\\Users\\jason\\Saved Games\\Frontier Developments\\Elite Dangerous\\",
  "hideJournalWriteTimer": false,
  "targetLatLong": {
    "lat": 63.102,
    "long": 117.1199
  },
  "targetLatLongActive": true,
  "autoShowBioSummary": true,
  "autoShowBioPlot": true,
  "autoShowPlotFSS": false,
  "autoShowGuardianSummary": true,
  "autoShowRamTah": true,
  "autoShowPlotSysStatus": true,
  "skipGasGiantDSS": true,
  "skipRingsDSS": false,
  "skipLowValueDSS": true,
  "skipLowValueAmount": 1000000,
  "autoTrackCompBioScans": true,
  "skipAnalyzedCompBioScans": true,
  "autoRemoveTrackerOnSampling": true,
  "useExternalData": false,
  "autoLoadPriorScans": true,
  "skipPriorScansLowValue": false,
  "skipPriorScansLowValueAmount": 1000000,
  "showCanonnSignalsOnRadar": true,
  "useSmallCirclesWithCanonn": true,
  "hideMyOwnCanonnSignals": true,
  "focusGameOnStart": true,
  "focusGameOnMinimize": true,
  "enableGuardianSites": true,
  "enableEarlyGuardianStructures": false,
  "disableRuinsMeasurementGrid": false,
  "disableAerialAlignmentGrid": false,
  "hidePlottersFromCombatSuits": false,
  "hideOverlaysFromMouse": true,
  "autoShowFlightWarnings": true,
  "highGravityWarningLevel": 1.0,
  "plotterOpacity": 50.0,
  "formMainLocation": "3040, 1078",
  "formLogsLocation": "0, 0, 0, 0",
  "formAllRuinsLocation": "0, 0, 0, 0",
  "formRuinsLocation": "0, 0, 0, 0",
  "formBeaconsLocation": "0, 0, 0, 0",
  "formMapEditor": "0, 0, 0, 0",
  "formRamTah": "0, 0, 0, 0",
  "mapShowNotes": true,
  "blinkTigger": 134217728,
  "blinkDuration": 3000,
  "processScreenshots": false,
  "addBannerToScreenshots": true,
  "deleteScreenshotOriginal": false,
  "useGuardianAerialScreenshotsFolder": true,
  "screenshotSourceFolder": "D:\\Users\\jason\\OneDrive\\Pictures\\Frontier Developments\\Elite Dangerous",
  "screenshotTargetFolder": "D:\\Users\\jason\\OneDrive\\Pictures\\Frontier Developments\\Elite Dangerous\\converted",
  "rotateAndTruncateAlphaAerialScreenshots": true,
  "aerialAltAlpha": 1200.0,
  "aerialAltBeta": 1550.0,
  "aerialAltGamma": 1600.0,
  "idxGuardianPlotter": 0,
  "migratedAlphaSiteHeading": false,
  "inferColor": "118, 178, 248",
  "inferTolerance": 25,
  "inferThreshold": 0.002,
  "dataFolder1100": true,
  "pubDataSettlementTemplate": 9,
  "pubDataGuardian": 9,
  "processIdx": 0
}
22:34:13: Watching folder: C:\Users\jason\Saved Games\Frontier Developments\Elite Dangerous\
22:34:13: Watching file: C:\Users\jason\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
22:34:13: updatePubData ...
22:34:13: isMigrationValid: True, dataFolder1100: True
22:34:13: Loaded 512 ruins, 30 beacons, 155 beacons
22:34:13: Using settlementTemplates.json from pubData
22:34:13: Reading settlementTemplates.json: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\settlementTemplates.json
22:34:13: SiteTemplate.Imported 13 templates
22:34:13: CodexRef init ...
22:34:13: loadCodexRef: reading codex/ref from disk
22:34:13: prepBioRef: reading bioRef from disk
22:34:13: loadOrganicRewards: reading organic rewards from disk
22:34:13: CodexRef init - complete
22:34:13: Main.newGame: has old game:False 
22:34:13: Game .ctor
22:34:13: Reading: Journal.2024-01-07T221716.01.log
22:34:13: Game.initializeFromJournal: BEGIN  (FID:), journals.Count:28
22:34:13: Loaded data from: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\F10288402-live.json
22:34:13: Changed hasLatLong: True, has nearBody: False, nearBody matches: False
22:34:13: setCurrentBody by name: Synuefe NU-M d8-37 A 1
22:34:13: setCurrentBody: No systemData - ignoring bodyName: Synuefe NU-M d8-37 A 1
22:34:13: Mode change NoFocus => MainMenu
22:34:13: Game.initSystemData: rewind to last FSDJump or CarrierJump
22:34:13: Game.initSystemData: last location: 'Synuefe NU-M d8-37' (1281871546699)
22:34:13: Reading: Journal.2024-01-07T120137.01.log
22:34:13: Game.initSystemData: found last FSDJump, to 'Synuefe NU-M d8-37' (1281871546699)
22:34:13: Loading SystemData for: 'Synuefe NU-M d8-37' (1281871546699)
22:34:13: Loaded data from: C:\Users\jason\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\systems\F10288402\Synuefe NU-M d8-37_1281871546699.json
22:34:13: walkDeep: count: 2
22:34:13: Game.initSystemData: Processing 97 journal items forwards...
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:51:09)
22:34:13: pubDataSettlementTemplate - local: 9, remote: 9
22:34:13: pubDataGuardian - local: 9, remote: 9
22:34:13: updatePubData - complete
22:34:13: Game.initSystemData: playForwards 'FSSDiscoveryScan' (07/01/2024 12:53:12)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:12)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:27)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:34)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:38)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:44)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:53)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:53:57)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:01)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:06)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:08)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:11)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:13)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:15)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:19)
22:34:13: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 12:55:26)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:26)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:30)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:34:13: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:37)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:48)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 12:55:58)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:55:58)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 12:56:03)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:56:03)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 12:57:14)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:57:14)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 12:57:22)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:57:22)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:57:50)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 12:57:55)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:57:55)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:57:58)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:58:04)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:58:13)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:58:19)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:58:25)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:58:39)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:58:43)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:58:51)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:58:54)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 12:59:00)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:59:01)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:59:15)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 12:59:20)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:59:21)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:59:52)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 12:59:55)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:59:55)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 12:59:59)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 12:59:59)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:00:16)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:00:21)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:00:29)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:00:32)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 13:00:40)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:00:41)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 13:00:44)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:00:45)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:00:53)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:00:56)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:01:00)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:01:07)
22:34:14: Game.initSystemData: playForwards 'FSSBodySignals' (07/01/2024 13:01:37)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:01:37)
22:34:14: Game.initSystemData: playForwards 'FSSAllBodiesFound' (07/01/2024 13:01:37)
22:34:14: Game.initSystemData: playForwards 'SAAScanComplete' (07/01/2024 13:05:12)
22:34:14: Game.initSystemData: playForwards 'SAASignalsFound' (07/01/2024 13:05:12)
22:34:14: Game.initSystemData: playForwards 'Scan' (07/01/2024 13:05:12)
22:34:14: Game.initSystemData: playForwards 'ApproachBody' (07/01/2024 13:06:29)
22:34:14: Game.initSystemData: playForwards 'CodexEntry' (07/01/2024 13:10:28)
22:34:14: Game.initSystemData: playForwards 'Touchdown' (07/01/2024 13:10:40)
22:34:14: Game.initSystemData: playForwards 'Disembark' (07/01/2024 13:10:46)
22:34:14: Game.initSystemData: playForwards 'ScanOrganic' (07/01/2024 13:11:13)
22:34:14: Game.initSystemData: playForwards 'Touchdown' (07/01/2024 13:17:24)
22:34:14: Game.initSystemData: playForwards 'Disembark' (07/01/2024 13:20:00)
22:34:14: Game.initSystemData: playForwards 'ScanOrganic' (07/01/2024 13:21:43)
22:34:14: Game.initSystemData: playForwards 'Disembark' (07/01/2024 13:22:47)
22:34:14: Game.initSystemData: playForwards 'ScanOrganic' (07/01/2024 13:22:58)
22:34:14: Game.initSystemData: playForwards 'ScanOrganic' (07/01/2024 13:23:03)
22:34:14: reCalcOrganicRewards: updated to: 3,283,500, was: 3,283,500
22:34:14: Game.initSystemData: playForwards 'ApproachBody' (07/01/2024 13:29:07)
22:34:14: Game.initSystemData: playForwards 'Touchdown' (07/01/2024 13:36:04)
22:34:14: Game.initSystemData: playForwards 'SAASignalsFound' (07/01/2024 13:42:10)
22:34:14: Game.initSystemData: playForwards 'ApproachBody' (07/01/2024 13:46:01)
22:34:14: Game.initSystemData: playForwards 'Touchdown' (07/01/2024 13:51:03)
22:34:14: Game.initSystemData: playForwards 'SAASignalsFound' (07/01/2024 13:56:51)
22:34:14: Game.initSystemData: playForwards 'SAASignalsFound' (07/01/2024 22:18:48)
22:34:14: Game.initSystemData: complete 'Synuefe NU-M d8-37' (1281871546699), bodyCount: 50
22:34:14: Game.initCargoData: rewind to last Cargo
22:34:14: Game.initCargoData: Processing 1 cargo journal items forwards...
22:34:14: Game.initCargoData: cargo playForwards 'Cargo' (07/01/2024 22:18:51)
22:34:14: Updating inventory, count: 0
22:34:14: Game.initCargoData: Current cargo:
  
22:34:14: setLocations: from Location: Synuefe NU-M d8-37 / Synuefe NU-M d8-37 A 1 (Planet)
22:34:14: Loading SystemData for: 'Synuefe NU-M d8-37' (1281871546699)
22:34:14: setCurrentBody by id: 3
22:34:14: this.fetchedSystemData = 'Synuefe NU-M d8-37'
22:34:14: this.fetchedSystemData = 'Synuefe NU-M d8-37' - complete
22:34:14: Game.initializeFromJournal: system: 'Synuefe NU-M d8-37' (id:1281871546699), body: 'Synuefe NU-M d8-37 A 1' (id:3, r: 8.35mm)
22:34:14: initFromJournal.walk: begin
22:34:14: Reading: Journal.2024-01-07T120137.01.log
22:34:14: Program.Creating plotter: PlotSysStatus
22:34:14: Searching journals for last touchdown location... (mode: MainMenu)
22:34:14: Reading: Journal.2024-01-07T120137.01.log
22:34:14: Found last touchdown location: Lat:+63.103237, Long:+117.120354
22:34:14: searchJournalsDeep: count: 2
22:34:14: Program.Showing plotter: PlotSysStatus
22:34:14: walkDeep: count: 2
22:34:14: initFromJournal.walk: found FSS: True, bodyCount: 50, count FSS: 62, count DSS: 1, count bio bodies: 6
22:34:14: Game.initializeFromJournal: END Commander:BRAMMMERS, starSystem:Synuefe NU-M d8-37, systemLocation:Synuefe NU-M d8-37 A 1, systemBody:'Synuefe NU-M d8-37 A 1' (3, LandableBody), journals.Count:28
22:34:14: Cmdr loaded: True
22:34:14: Program.Creating plotter: PlotPulse
22:34:14: Program.Showing plotter: PlotPulse
22:34:14: migratedScannedOrganicsInEntryId: True, migratedNonSystemDataOrganics: True

**Comment by njthomson** [comment]
Thank you @brammmers - the error `IOException:The process cannot access the file xxx` is a rare timing issue, a race hazard between logs getting written in parallel between different threads.

It will be fixed in the next build.

**Comment by njthomson** [comment]
@brammmers - these issues should be fixes with build https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.6
