### ISSUE TITLE
Exception "Unexpected entryId: '2100804'" at 1/17/2024 10:09:11 PM -05:00

### ISSUE THREAD

**Issue by rbradh53** [njthomson/SrvSurvey#42]
### What happened?

Again, it just quit working.
It's a great program, my squad mates and I love this program. Don't see how we managed without it.

### Version

1.1.0.10

### Exception message

Unexpected entryId: '2100804'

### Exception stack

   at SrvSurvey.canonn.CodexRef.matchFromEntryId(String entryId)
   at SrvSurvey.canonn.CodexRef.matchFromEntryId(Int64 entryId)
   at SrvSurvey.game.Game.onJournalEntry(CodexEntry entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1701","build":"r298704/r0 ","timestamp":"2024-01-17T23:01:57Z","event":"Fileheader"}
22:04:47: Program.Closing plotter: PlotSysStatus
22:04:58: Mode change GlideMode => Flying
22:05:42: Mode change Flying => Landed
22:05:42: Program.Creating plotter: PlotGrounded
22:05:42: Program.Showing plotter: PlotGrounded
22:05:42: initialize here: Lat:-3.421106, Long:-107.819199, touchdownLocation: Lat:+0.000000, Long:+0.000000, radius: 2,783,714
22:05:43: Mode change Landed => RolePanel
22:05:45: Mode change RolePanel => Landed
22:05:50: Mode change Landed => OnFoot
22:06:07: Mode change OnFoot => Landed
22:06:10: Mode change Landed => Flying
22:06:35: Mode change Flying => Landed
22:06:42: Mode change Landed => OnFoot
22:07:08: Mode change OnFoot => Landed
22:07:10: Mode change Landed => Flying
22:07:32: Mode change Flying => Landed
22:07:33: Mode change Landed => RolePanel
22:07:34: Mode change RolePanel => Landed
22:07:39: Mode change Landed => OnFoot
22:08:00: Mode change OnFoot => Landed
```

**Comment by njthomson** [comment]
Thank you @rbradh53 for reporting this. It is due to a biological signal not previously known. I will work on a fix.

**Comment by njthomson** [comment]
A fix will be present in the next build.

**Comment by njthomson** [comment]
@rbradh53  - please try this build and let me know if it keeps happening: https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.20
