### ISSUE TITLE
ArgumentException "Requested value 'PlanetaryRing' was not found." at 1/23/2024 3:33:58 PM -08:00

### ISSUE THREAD

**Issue by Wolfhauler** [njthomson/SrvSurvey#45]
### What happened?

spawned landed and this is the issue that came up when i opened the app, im in  a anaconda if that helps!

### Version

1.1.0.17

### Exception message

Requested value 'PlanetaryRing' was not found.

### Exception stack

   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

**Comment by Wolfhauler** [comment]
}
15:35:04: Reading PlotterPositions from: C:\Users\(myname)\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\plotters.json
15:35:04: Program.repositionPlotters: 0, rect{X=0,Y=0,Width=0,Height=0}
15:35:04: Watching folder: C:\Users\(myname)\Saved Games\Frontier Developments\Elite Dangerous\
15:35:04: Watching file: C:\Users\(myname)\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
15:35:04: isMigrationValid: False, dataFolder1100: True
15:35:04: updatePubData ...
15:35:05: Loaded 512 ruins, 30 beacons, 155 beacons
15:35:05: Using settlementTemplates.json from pubData
15:35:05: Reading settlementTemplates.json: C:\Users\(myname)\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\settlementTemplates.json
15:35:05: SiteTemplate.Imported 13 templates
15:35:05: CodexRef init ...
15:35:05: loadCodexRef: reading codex/ref from disk
15:35:05: prepBioRef: reading bioRef from disk
15:35:05: loadOrganicRewards: reading organic rewards from disk
15:35:05: CodexRef init - complete
15:35:05: Main.newGame: has old game:False 
15:35:05: Game .ctor
15:35:05: pubDataSettlementTemplate - local: 16, remote: 16
15:35:05: pubDataGuardian - local: 16, remote: 16
15:35:05: updatePubData - complete
15:35:05: Reading: Journal.2024-01-23T153112.01.log
15:35:05: Game.initializeFromJournal: BEGIN  (FID:), journals.Count:10
15:35:05: Loaded data from: C:\Users\(myname)\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\F5256735-live.json
15:35:05: Game.initSystemData: rewind to last FSDJump or CarrierJump
15:35:05: Game.initSystemData: last location: 'Synuefe WU-V b35-3' (7269902787889)
15:35:05: Reading: Journal.2024-01-23T085211.01.log
15:35:05: Exception: Requested value 'PlanetaryRing' was not found.
15:35:05: Inner exception: 
15:35:05: Stack:    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

**Comment by Wolfhauler** [comment]
15:35:05: Reading: Journal.2024-01-23T085211.01.log something in the log fucked maybe?

**Comment by njthomson** [comment]
Thank you @Wolfhauler for reporting this. Did it keep happening in that same system?

**Comment by Wolfhauler** [comment]
it never happened again after i left the planet i spawned on

**Comment by Wolfhauler** [comment]
01:40:48: SrvSurvey version: 1.1.0.17
01:40:48: New log file: C:\Users\myname\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240127_014048.txt
01:40:48: dataFolder: C:\Users\myname\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0
01:40:48: Removing old log file: C:\Users\myname\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240123_154016.txt
01:40:48: Loaded settings: {
  "preferredCommander": null,
  "lastCommander": "wolfhauler",
  "lastFid": "F5256735",
  "watchedJournalFolder": "C:\\Users\\myname\\Saved Games\\Frontier Developments\\Elite Dangerous\\",
  "hideJournalWriteTimer": false,
  "targetLatLong": {
    "lat": 0.0,
    "long": 0.0
  },
  "targetLatLongActive": false,
  "autoShowBioSummary": true,
  "autoShowBioPlot": true,
  "autoShowPlotFSS": true,
  "autoShowGuardianSummary": true,
  "autoShowRamTah": true,
  "autoShowPlotSysStatus": true,
  "skipGasGiantDSS": false,
  "skipRingsDSS": true,
  "skipLowValueDSS": true,
  "skipLowValueAmount": 1000000,
  "autoTrackCompBioScans": true,
  "skipAnalyzedCompBioScans": true,
  "autoRemoveTrackerOnSampling": true,
  "useExternalData": true,
  "autoLoadPriorScans": true,
  "skipPriorScansLowValue": true,
  "skipPriorScansLowValueAmount": 2000000,
  "showCanonnSignalsOnRadar": true,
  "useSmallCirclesWithCanonn": true,
  "hideMyOwnCanonnSignals": true,
  "focusGameOnStart": true,
  "focusGameOnMinimize": true,
  "enableGuardianSites": true,
  "enableEarlyGuardianStructures": false,
  "disableRuinsMeasurementGrid": false,
  "disableAerialAlignmentGrid": false,
  "hidePlottersFromCombatSuits": false,
  "hideOverlaysFromMouse": true,
  "autoShowFlightWarnings": true,
  "highGravityWarningLevel": 1.0,
  "plotterOpacity": 50.0,
  "formMainLocation": "-389, 172",
  "formLogsLocation": "0, 0, 0, 0",
  "formAllRuinsLocation": "0, 0, 0, 0",
  "formRuinsLocation": "0, 0, 0, 0",
  "formBeaconsLocation": "0, 0, 0, 0",
  "formMapEditor": "0, 0, 0, 0",
  "formRamTah": "0, 0, 0, 0",
  "mapShowNotes": true,
  "blinkTigger": 134217728,
  "blinkDuration": 3000,
  "processScreenshots": false,
  "addBannerToScreenshots": true,
  "deleteScreenshotOriginal": false,
  "useGuardianAerialScreenshotsFolder": true,
  "screenshotSourceFolder": "C:\\Users\\myname\\Pictures\\Frontier Developments\\Elite Dangerous",
  "screenshotTargetFolder": "C:\\Users\\myname\\Pictures\\Frontier Developments\\Elite Dangerous\\converted",
  "rotateAndTruncateAlphaAerialScreenshots": true,
  "aerialAltAlpha": 1200.0,
  "aerialAltBeta": 1550.0,
  "aerialAltGamma": 1600.0,
  "idxGuardianPlotter": 0,
  "migratedAlphaSiteHeading": false,
  "inferColor": "102, 255, 255",
  "inferTolerance": 25,
  "inferThreshold": 0.002,
  "dataFolder1100": true,
  "pubDataSettlementTemplate": 18,
  "pubDataGuardian": 18,
  "processIdx": 0
}
01:40:48: Reading PlotterPositions from: C:\Users\myname\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\plotters.json
01:40:48: Program.repositionPlotters: 0, rect{X=0,Y=0,Width=0,Height=0}
01:40:48: Watching folder: C:\Users\myname\Saved Games\Frontier Developments\Elite Dangerous\
01:40:48: Watching file: C:\Users\myname\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
01:40:48: isMigrationValid: False, dataFolder1100: True
01:40:48: updatePubData ...
01:40:48: Loaded 512 ruins, 30 beacons, 155 beacons
01:40:48: Using settlementTemplates.json from pubData
01:40:48: Reading settlementTemplates.json: C:\Users\myname\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\settlementTemplates.json
01:40:48: SiteTemplate.Imported 13 templates
01:40:48: CodexRef init ...
01:40:48: loadCodexRef: reading codex/ref from disk
01:40:48: prepBioRef: reading bioRef from disk
01:40:48: loadOrganicRewards: reading organic rewards from disk
01:40:48: CodexRef init - complete
01:40:48: Main.newGame: has old game:False 
01:40:48: Game .ctor
01:40:48: Reading: Journal.2024-01-27T010757.01.log
01:40:48: pubDataSettlementTemplate - local: 18, remote: 18
01:40:48: pubDataGuardian - local: 18, remote: 18
01:40:48: updatePubData - complete
01:40:48: Game.initializeFromJournal: BEGIN  (FID:), journals.Count:11
01:40:48: Loaded data from: C:\Users\myname\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\F5256735-live.json
01:40:48: Game.initSystemData: rewind to last FSDJump or CarrierJump
01:40:48: Game.initSystemData: last location: '60 Tauri' (3515170670939)
01:40:48: Reading: Journal.2024-01-26T180052.01.log
01:40:48: Exception: Requested value 'PlanetaryRing' was not found.
01:40:48: Inner exception: 
01:40:48: Stack:    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   
   
   
   I spawned on Miletus orbital in 60 tauri system and it happened again it seems to not like spawning not in space?

**Comment by Wolfhauler** [comment]
i jumped and relaunched the app and it worked all of the sudden

**Comment by njthomson** [comment]
@Wolfhauler - I suspect it will happen if you return to that system. If it does, could you share the relayed journal file?

**Comment by Wolfhauler** [comment]
im 30 jumps away, but thats cause im doing the journey for gaurian unlocks on my way back i will indeed

**Comment by Wolfhauler** [comment]
yes it gave me the same error and log in that system

**Comment by njthomson** [comment]
@Wolfhauler - which build are you using?

**Comment by Wolfhauler** [comment]
1.0.1.17 just updated right before i saw this now using latest

**Comment by Wolfhauler** [comment]
gonna close this now as you said it was fixed, thanks!
