### ISSUE TITLE
Request: More screenshot configuration options

### ISSUE THREAD

**Issue by Vic502** [njthomson/SrvSurvey#53]
1st: Thanks for a great tool!

Regarding the screenshot conversions:
It'd be good if there were some additional configuration options, e.g.:

1. Change the imbedded time to local time.
2. Change the colour of the imbedded info.
3. Configure the folder where the conversions are stored, i.e. I prefer folders by date & time (e.g. 20240204-073800)

Cheers!

**Comment by njthomson** [comment]
Thanks @Vic502 for the suggestions. The first 2 can be added easily.

Adding a date part to the folders used will be problematic - I rely on consistent folder names to correlate Guardian site images. Besides, would a date part in folders lead to a large number of folders over time?

**Comment by njthomson** [comment]
@Vic502 - this build has those first two: https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.39

**Comment by Vic502** [comment]
Thanks, will check it out.

Regarding folders, I mean, not folders by time, just date.  But I understand the butterfly effect if you change it, so no worries.

**Comment by njthomson** [comment]
@Vic502 - righty ho. Let me know if those first two ideas are working out for you.
