### ISSUE TITLE
Exception "Unexpected entryId: '2100801'" at 22-02-2024 20:58:09 -04:00

### ISSUE THREAD

**Issue by AuerXX** [njthomson/SrvSurvey#69]
### What happened?

using comp scanner

### Version

1.1.0.44

### Exception message

Unexpected entryId: '2100801'

### Exception stack

   at SrvSurvey.canonn.CodexRef.matchFromEntryId(String entryId)
   at SrvSurvey.canonn.CodexRef.matchFromEntryId(Int64 entryId)
   at SrvSurvey.game.Game.onJournalEntry(CodexEntry entry)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

**Comment by njthomson** [comment]
Thanks @AuerXX - were you on a planet or using the Comp Scanner at some Notable Stella Phenomenon?

**Comment by AuerXX** [comment]
I was scanning an NSP

**Comment by njthomson** [comment]
@AuerXX - will you let me know if this happens again with a more recent build?
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.50

And if it does, which system you were in at the time?

**Comment by AuerXX** [comment]
Sure, not close an NSP by now, but I hope soon will be, will let you know
