### ISSUE TITLE
SrvSurvey

### ISSUE THREAD

**Issue by Siggi28261** [njthomson/SrvSurvey#7]
Hi, maybe I missed something there. But a more detailed guide would be nice.
Thanks in advance
Siggi

**Comment by McJorgan** [comment]
I am also having a lot of trouble wrapping my head around getting this plugin to run from step 1. I can't find an exe to run it standalone, or a zip in the folders that I can use with edmc overlay. Any help, or even a simple step-by-step to install, would be greatly appreciated!

**Comment by njthomson** [comment]
Thank you both for the feedback.

@Siggi28261 - there is some guidance for bio-scanning at [https://njthomson.github.io/SrvSurvey/](https://njthomson.github.io/SrvSurvey/) but this needs a thorough re-write now that Guardian Ruins features are ready.

In the mean time, [this video](https://photos.onedrive.com/share/A8DE3BF2C01304C4!312081?cid=A8DE3BF2C01304C4&authkey=!AOxR529bMUZbMmw&ithint=video&e=RZA90Y) shows those Guardian Ruin features in action.

@McJorgan - this tool is an independent application, not related to EDMC. Running `setup.exe` in the .zip file will install it. Though as an unsigned build it will come with scary trust warnings, click the `More info` link to proceed.

**Comment by McJorgan** [comment]
> Thank you both for the feedback.
> 
> @Siggi28261 - there is some guidance for bio-scanning at https://njthomson.github.io/SrvSurvey/ but this needs a thorough revision now that Guardian Ruins features are ready.
> 
> In the mean time, [this video](https://photos.onedrive.com/share/A8DE3BF2C01304C4!312081?cid=A8DE3BF2C01304C4&authkey=!AOxR529bMUZbMmw&ithint=video&e=RZA90Y) shows those Guardian Ruin features in action, though recent improvements mean that the tool will already know the site type.
> 
> @McJorgan - this tool is an independent application, not related to EDMC. You can download the latest version as a .zip file from [Latest release 1.0.8.2](https://github.com/njthomson/SrvSurvey/releases/tag/1.0.8.2), and run `setup.exe` in that .zip file to install it. As an unsigned build it will come with scary trust warnings needing you to click the `More info` link to proceed.

I appreciate your quick response and your help! Have a great day and keep up the excellent work. Your tool is brilliant.

**Comment by njthomson** [comment]
> > Thank you both for the feedback.
> > @Siggi28261 - there is some guidance for bio-scanning at https://njthomson.github.io/SrvSurvey/ but this needs a thorough revision now that Guardian Ruins features are ready.
> > In the mean time, [this video](https://photos.onedrive.com/share/A8DE3BF2C01304C4!312081?cid=A8DE3BF2C01304C4&authkey=!AOxR529bMUZbMmw&ithint=video&e=RZA90Y) shows those Guardian Ruin features in action, though recent improvements mean that the tool will already know the site type.
> > @McJorgan - this tool is an independent application, not related to EDMC. You can download the latest version as a .zip file from [Latest release 1.0.8.2](https://github.com/njthomson/SrvSurvey/releases/tag/1.0.8.2), and run `setup.exe` in that .zip file to install it. As an unsigned build it will come with scary trust warnings needing you to click the `More info` link to proceed.
> 
> I appreciate your quick response and your help! Have a great day and keep up the excellent work. Your tool is brilliant.

@McJorgan - please take a look at:
[https://github.com/njthomson/SrvSurvey/blob/main/README.md](https://github.com/njthomson/SrvSurvey/blob/main/README.md)

**Comment by njthomson** [comment]
@Siggi28261 - please take a look at [https://github.com/njthomson/SrvSurvey/blob/main/README.md](https://github.com/njthomson/SrvSurvey/blob/main/README.md)
