### ISSUE TITLE
Add "disable audio" setting

### ISSUE THREAD

**Issue by jansaell** [njthomson/SrvSurvey#73]
HI there!

The program is wonderful and really helps on foot exploration and exo-biology.

Just running it by itself is a gear way, but i just installed ED Copilot also and that program also announcing info about exo-biology.

You map is very helpful so i would like to run both but having the sound only from ED Copilot.

Can you add that?

Keep up to good work
Jan

**Comment by njthomson** [comment]
Hi @jansaell - I must confess I am a bit confused as SrvSurvey doesn't produce any sound.

What is the audio you wish to remove?

**Comment by jansaell** [comment]
It must be some other plugin / app i have then - so skipp this then.

Still think you porgram / app is wounderfull.

**Comment by jansaell** [comment]
closing
