### ISSUE TITLE
unclaimed map/scan value reward

### ISSUE THREAD

**Issue by Minecrafter8001** [njthomson/SrvSurvey#74]
Since SRV Survey knows the estimated scan value of planets when scanned in the FFS, could you add a section for unclaimed exploration data? No other tool seems to do this, and it would be very useful to know.

**Comment by Minecrafter8001** [comment]
oh also does it automaitcly apply a first mapped/discovered bonus to the overlay in the FSS?

**Comment by njthomson** [comment]
This is a good suggestion, and I don't think would be too hard.

**Comment by Minecrafter8001** [comment]
thanks : )

**Comment by Minecrafter8001** [comment]
oh also would it be possible for you to add a range filter to the exploration tab in settings?
its a bit annoying when it recommends planets 100,000LS away from the main star

**Comment by njthomson** [comment]
Let me see what I can do.

**Comment by njthomson** [comment]
@Minecrafter8001 - the distance filter has been implemented in this build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.57

**Comment by Minecrafter8001** [comment]
sweet
is that build available on the MS store?

**Comment by njthomson** [comment]
@Minecrafter8001 within a week.

**Comment by njthomson** [comment]
This build cleared the MS store faster than usual. You can download it from:
https://www.microsoft.com/store/productId/9NGT6RRH6B7N

**Comment by njthomson** [comment]
@Minecrafter8001 - this has been implemented in recent builds, though it may take a while for it to hit the MS app store.

**Comment by njthomson** [comment]
@Minecrafter8001 - at long last, this ability is available in the Windows app store.
