### ISSUE TITLE
app not detecting game after restart

### ISSUE THREAD

**Issue by Minecrafter8001** [njthomson/SrvSurvey#75]
If I restart my game, I have to relaunch the app for it to detect that the game is running again. I'd assume this is because it only checks for the application/new journal file on launch. Perhaps you could update it to automatically check every 30 seconds to a minute if the program isn't detected? This isn't really an "issue" more of a QOL thing, so if you don't change it its fine.

**Comment by njthomson** [comment]
@Minecrafter8001 - I'm assuming the game isn't crashing here? It should (and for me it does) handle restarts, even with different commanders. Does SrvSurvey identify that the game stops?

Could you share a log file from SrvSurvey at the point you restarted the game and SrvSurvey failed re-initialize for it.

**Comment by Minecrafter8001** [comment]
i didn't realise this would be a bug so i don't have that info lemme test it on my end

**Comment by Minecrafter8001** [comment]
it may not do it anymore since there has been a computer restart since

**Comment by Minecrafter8001** [comment]
ok i launched SRV survey without the game running and launched ED and it didn't detect it
![image](https://github.com/njthomson/SrvSurvey/assets/133237713/b6804eba-66d6-444a-9cc6-4dfa5a043f47)
srv survey log:
[srvs-20240307_115015.txt](https://github.com/njthomson/SrvSurvey/files/14523577/srvs-20240307_115015.txt)
journal file for this launch:
[Journal.2024-03-07T115209.01.log](https://github.com/njthomson/SrvSurvey/files/14523580/Journal.2024-03-07T115209.01.log)

**Comment by njthomson** [comment]
@Minecrafter8001 - I understand the reason this is happening. When the game starts a journal file is created when the main menu appears but the particular cmdr isn't known until you start playing the actual game.

You have SrvSurvey set to ignore cmdr's except _minecrafter_. When the journal file is created at the main menu the cmdr isn't _minecrafter_ (or anything really) so it is ignored. The code keeps going looking at progressively older journal files until it finds one for _minecrafter_ - which would be the journal from your last session. Predictably, that last journal knows the game ended, so SrvSurvey assumed there's no active session for _minecrafter_. Whilst you're at the main menu this is actually true. Whilst once you start playing the cmdr would be known, but the journal file already exists and SrvSurvey is not watching it, it's looking our for new journal files but none are created until the game is restarted.

This problem would not occur if you set `Preferred Commander` setting to `(no preference)`:
![image](https://github.com/njthomson/SrvSurvey/assets/3903773/892be7af-5095-46ed-8dbe-23b5fc447a1f)

**Comment by Minecrafter8001** [comment]
oops XD 
i don't remember setting that but oh well

**Comment by Minecrafter8001** [comment]
i was dumb lmao
