### ISSUE TITLE
Movers and Shakers

### ISSUE THREAD

**Issue by Trickyhicky** [njthomson/SrvSurvey#76]
Hey, NJ loving the SRV Survey overlays, being into the exploration side of Elite they make the game more immersive for me. 

Can I ask if there are any plans to be able to move the overlays about our screen? 

The reason I ask is that I run a few other add-ons to the game one being the EDMC which I like to have on the right of my screen currently the SRV Sur Overlay is directly showing under it and no matter how I try I can't grab the SRVSur overlay to move it to another position on my screen or screens.  

One other thing I have noticed as well is if I move my mouse with the SRVSur it tends to judder and lose accuracy, now this only occurs when SRVSur is running.  Not sure how to illustrate this phenomenon to send to you to show what occurs.

Thanks for all your hard work.

Phil

**Comment by njthomson** [comment]
Hi @Trickyhicky - glad to hear you are enjoying SrvSurvey.

Each of the overlays can be relocated against the game window or your desktop by modifying file `%appdata%\SrvSurvey\SrvSurvey\1.1.0.0\plotters.json` - see https://github.com/njthomson/SrvSurvey/wiki/Custom-overlay-positioning for full details.

**Comment by njthomson** [comment]
For the mouse juddering ... this might be caused by SrvSetting setting `Prevent mouse entering overlay windows`. Does the issue still occur if you change it?

![image](https://github.com/njthomson/SrvSurvey/assets/3903773/17d70f91-4a0e-463a-8448-1f45f3e134f5)

Previously ... people had reported troubles when the mouse happened to be over an overlay and they clicked to fire weapons which lost focus from the game. To mitigate that, this setting forces the mouse location back to screen center any time it overlaps one of the overlays. The mouse is not visible during this so it's not obvious what is going on, and it feels weird as the mouse should have become visible if you move it far enough but it never shows.

**Comment by Trickyhicky** [comment]
Hi @njthomson I have got the Prevent Moiuse checked now so will see how it goes when next up.  I will also look at the way you have described but as someone who has a passing understanding of how my computer works, I'm not sure my skill set is up to what I have looked at so far. 
Thanks for all your hard work and for getting back to me so quickly it is very much appreciated.
Phil

**Comment by Trickyhicky** [comment]
Hi @njthomson I have searched for the .json file in various ways but have been unable to track it down. Do you have any suggestions please?

**Comment by njthomson** [comment]
@Trickyhicky are you using SrvSurvey from the Microsoft App store? That version doesn't have that file yet but it will within a week.

**Comment by njthomson** [comment]
The Microsoft App store version has been updated already:
https://www.microsoft.com/store/productId/9NGT6RRH6B7N?ocid=pdpshare

**Comment by Trickyhicky** [comment]
Found it after an hour of searching here various combinations, see I told you I was a dumb arse, still got there in the end. I will have a play with the settings when I next have ED running.
C:\Users\Username)\AppData\Local\Packages\35333NosmohtSoftware.142860789C73F_p4c193bsm1z5a\LocalCache\Roaming\SrvSurvey

Thanks for your help

Phil

**Comment by njthomson** [comment]
@Trickyhicky - I am impressed that you found that file there - though I worry it may not be the right one. Do you see the file `SrvSurvey.exe` in the same folder? A copy of `plotters.json` gets installed with the app to be used as the initial default, which is copied when running SrvSurvey. It is the copy that needs to be edited. (And the copy won't exist until you've run SrvSurvey once after installing the new version)

However this should be easier than I remembered. The exact location will be listed in SrvSurvey logs, look for a line like this ...

    10:35:30: Reading PlotterPositions from: C:\Users\grinn\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\plotters.json

... which is the first row after the long list of initial settings:

![image](https://github.com/njthomson/SrvSurvey/assets/3903773/97ea4d4c-653a-4ca2-9f40-a83fa307c064)

**Comment by njthomson** [comment]
@Trickyhicky - I recently learned that the folders shown in SrvSurvey were not the folders used by the OS. This has been recently fixed - please give it another go and let me know if you're able to shift the overlays about.

**Comment by njthomson** [comment]
I'm closing out this old issue, but please don't hesitate to re-open or create a new one if SrvSurvey gives you any grief.

**Comment by Trickyhicky** [comment]
Thank You very much for your work.
