### ISSUE TITLE
False bio data readout

### ISSUE THREAD

**Issue by Minecrafter8001** [njthomson/SrvSurvey#77]
SRV survey seems to think I have 7 more bio samples to sell when I don't?
![image](https://github.com/njthomson/SrvSurvey/assets/133237713/415c619b-d138-44da-b479-6648612f0fae)

**Comment by njthomson** [comment]
Could you share the SrvSurvey log file from when you sold the organic data?

And, do recall if you had a total ofn7 before hand or more? Meaning: did it reduce some or not all all?

**Comment by Minecrafter8001** [comment]
i don't have that log file anymore 
ill update this post if selling or acquiring more data fixes it

**Comment by Minecrafter8001** [comment]
> @Minecrafter8001 - Could you share the SrvSurvey log file from when you sold the organic data?
> 
> And, do recall if you had a total of 7 before hand or more? Meaning: did it reduce some or not all all?

SRV survey reported I had over 30 exobio data and i sold it all at once so it cleared some but not all

**Comment by Minecrafter8001** [comment]
im looking through my journal files rn to see if i can find when i sold the bio data

**Comment by Minecrafter8001** [comment]
I can fix it by deleting my "specicesRewards.json" file but I'm not going to so I can see how this bug works and give you logs to help you fix it

btw here is that file if you wanted to look at it:
[speciesRewards.json](https://github.com/njthomson/SrvSurvey/files/14547624/speciesRewards.json)

**Comment by Minecrafter8001** [comment]
[Journal.2024-03-07T151039.01.log](https://github.com/njthomson/SrvSurvey/files/14547636/Journal.2024-03-07T151039.01.log)
Here's the journal file for when I sold the data as well (line 967)

**Comment by njthomson** [comment]
Thank you @Minecrafter8001 - these will be helpful.

**Comment by njthomson** [comment]
There's a button settings to reset your count to zero - if it's annoying you. I don't think there's any benefit for my research you keeping those around any more.

**Comment by Minecrafter8001** [comment]
ok ill reset it

**Comment by njthomson** [comment]
Let me know if you see this again.
