### ISSUE TITLE
automatically selecting first footfall when exiting SRV

### ISSUE THREAD

**Issue by Minecrafter8001** [njthomson/SrvSurvey#80]
[srvs-20240315_184850.txt](https://github.com/njthomson/SrvSurvey/files/14620161/srvs-20240315_184850.txt)
[Journal.2024-03-15T185059.01.log](https://github.com/njthomson/SrvSurvey/files/14620163/Journal.2024-03-15T185059.01.log)

every time i leave my SRV SRV survey enables first footfall even if ive disabled it for this planet

**Comment by Minecrafter8001** [comment]
in the log you can see me disabling FF but never enabling it

**Comment by njthomson** [comment]
@Minecrafter8001 - the auto-first footfall works by looking for lots of blue pixels once you step outside your ship. Have you customized HUD colours? Is this happening for all bodies, or only some?

**Comment by Minecrafter8001** [comment]
i haven't changed my hud colours
and its been at night most of the time
the only thing thats changed is im now using a HOTAS with ED but i doubt that has anything to do with it

**Comment by njthomson** [comment]
Hmm. Could you share a screenshot from about 5 seconds after you step out on foot? The code is finding something blue.

**Comment by Minecrafter8001** [comment]
sorry only just saw this ill test it now

**Comment by Minecrafter8001** [comment]
though i have updated to the latest version now so it may have fixed itself

**Comment by Minecrafter8001** [comment]
yeah after updating it seems to have fixed itself
ill reopen this if i have this issue again
