### ISSUE TITLE
Move "Clear Tracked Locations" to main panel.

### ISSUE THREAD

**Issue by Vic502** [njthomson/SrvSurvey#88]
Describe your suggestion ...
Tracked locations are super useful when doing exobiology.  However, I often have to clear the tracked locations.  Is it possible to move this button from settings to the main panel (maybe next to the First Footfall tick box or something)?

**Comment by Vic502** [comment]
I'm using version 1.1.1.4.  But yeah, will try those commands, thanks.  Thing is I don't always go back to the exact samples I've tracked, so then I'm sometimes left with leftovers.  When scanning one sample, I'll mark a lot of others, to make it easier when I get to the next species.

**Comment by Vic502** [comment]
Hmmm.  "---" to Local, closes/exits/crashes my SRV Survey app when in supercruise.  Let me try on a planet.

**Comment by Vic502** [comment]
On a planet it works, thanks.

**Comment by njthomson** [comment]
> Hmmm. "---" to Local, closes/exits/crashes my SRV Survey app when in supercruise. Let me try on a planet.

This will be fixed in the next build.

**Comment by njthomson** [comment]
@Vic502 - do you feel using `---` will be sufficient for you?

**Comment by Vic502** [comment]
Yes, I think "---" will be fine, thanks.

**Comment by njthomson** [comment]
Excellent - thank you.
