### ISSUE TITLE
DirectoryNotFoundException "Could not find a part of the path 'C:\Users\Rob\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\guardian'." at 28/03/2024 23:54:06 +00:00

### ISSUE THREAD

**Issue by rah99** [njthomson/SrvSurvey#89]
### What happened?

Went to close the program as it  was not working properly - it was not creating the last scanned bio diversity circle, basically it created the first circle of the bio scanned and continued to register it as the only scanned bio evn though I had scanned others of the same. I see the exception is related to "guardian" - this will be empty in my case as I have not used it at guardian sites yet - done most of that before I found this app. 

### Version

1.1.2.0

### Exception message

Could not find a part of the path 'C:\Users\Rob\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\pub\guardian'.

### Exception stack

   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at SrvSurvey.game.GuardianSitePub.Find(String systemName)
   at SrvSurvey.game.SystemData.prepSettlements()
   at SrvSurvey.game.Game.onJournalEntry(Embark entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

**Comment by rah99** [comment]
Update - I uninstalled and reinstalled SRV Survey - so all working now. The issues started with the update where the program could not or did not update as I expect it should - it got stuck "Reticulating data..." (I left it for over an hour like this whilst doing RL stuff). On reinstalling SRV Survey I moved the AppData from the previous version to a different location (on a new install the data was causing the same/similar issues with the new install so it needed to be removed) and not deleted it so as it can be reviewed if you need it for resolving the bug.

**Comment by njthomson** [comment]
Thank you @rah99 for reporting this.

Would you be willing to share the pre-migration backup .zip from the AppData folder? (It's up one level in the parent folder)

**Comment by njthomson** [comment]
The `DirectoryNotFoundException` error will be fixed in the next build.

**Comment by rah99** [comment]
OK think this is the .zip file you mentioned - may not be the right one mind you as not sure if it got replaced - soz if it is not the one you are looking for:
[pre-migration-backup-20240331_182854.zip](https://github.com/njthomson/SrvSurvey/files/14829427/pre-migration-backup-20240331_182854.zip)

Also attached please find the logs - sending the whole file as I tried a free times to get it right:
[logs.zip](https://github.com/njthomson/SrvSurvey/files/14829453/logs.zip)

**Comment by rah99** [comment]
Forgot to add - let me know if you need more info or files as I still have the SRV Survey AppData folder on my desktop.

**Comment by njthomson** [comment]
@rah99 - could you also share this file? It always gets stuck after read it:
C:\Users\Rob\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\systems\F10489717\Gludgoea KZ-Z b41-9_20409819275113.json

Or better yet - would you zip and share the whole AppData\SrvSurvey folder?

**Comment by njthomson** [comment]
@rah99 - the above files are **perfect!**

I've found and fixed an elusive migration bug that would never occur for me on my system - thank you.

The next GitHub build will have the fix later today, the Microsoft App store takes a number of days for publishing.

**Comment by njthomson** [comment]
The MS app store update published already, please give it a try and let me know how it goes.

**Comment by rah99** [comment]
Will do, did uninstall the offending app and reinstalled the other day but will def try again and let you know how it went - might try to use the olf data from 1.0.0.0 as it would be nice to migrate it all over.

**Comment by rah99** [comment]
So I uninstalled the app and added the JSON's from 1.1.0.0 to 1.0.0.0 F..... folder, the updater ran perfectly - did see some failures in the log file but the upload did not fail. Cheers for the fix is nice to retain most of my exo data so I don't end up landing somewhere to find out I have already done it - then I could check that in the system map before I go and land somewhere I guess hehehe.

**Comment by njthomson** [comment]
Thank you @rah99  for confirming the fix.
