### ISSUE TITLE
HttpRequestException "Response status code does not indicate success: 500 (Internal Server Error)." at 2024-04-05 7:37:13 AM -03:00

### ISSUE THREAD

**Issue by KilrSkwerl** [njthomson/SrvSurvey#91]
### What happened?

The app, from the Windows Store. need to do a "one time update" and then failed to launch. I uninstalled and then reinstalled from the Windows Store and got the same error on launch.

### Version

1.1.3.0

### Exception message

Response status code does not indicate success: 500 (Internal Server Error).

### Exception stack

   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at SrvSurvey.canonn.CodexRef.loadCodexRef()
   at SrvSurvey.canonn.CodexRef.init(Boolean reset)
   at SrvSurvey.net.Git.refreshPublishedData()

### Relevant log output

```shell
07:35:00: New log file: C:\Users\KilrS\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\logs\srvs-20240405_073500.txt
07:35:00: dataFolder: C:\Users\KilrS\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0
07:35:00: Creating new settings file: C:\Users\KilrS\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\settings.json
07:35:01: Resetting custom overlay positions
07:35:01: Reading PlotterPositions from: C:\Users\KilrS\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\plotters.json
07:35:01: Program.repositionPlotters: 0, rect{X=0,Y=0,Width=0,Height=0}
07:35:01: Watching folder: C:\Users\KilrS\Saved Games\Frontier Developments\Elite Dangerous\
07:35:01: Watching file: C:\Users\KilrS\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\DisplaySettings.xml
07:35:01: setFocusED: got Zero!
07:35:01: isMigrationValid: False, dataFolder1100: False
07:35:01: Using settlementTemplates.json app package
07:35:01: Reading settlementTemplates.json: C:\Program Files\WindowsApps\35333NosmohtSoftware.142860789C73F_1.1.3.0_x64__p4c193bsm1z5a\SrvSurvey\settlementTemplates.json
07:35:01: SiteTemplate.Imported 13 templates
07:35:01: updatePubData ...
07:35:03: pubDataSettlementTemplate - local: 0, remote: 25
07:35:03: Updating CodexRef ...
07:35:03: CodexRef init (reset: True) ...
07:35:03: loadCodexRef: preparing from network ...
07:35:05: Error in updatePubData:
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at SrvSurvey.canonn.CodexRef.loadCodexRef()
   at SrvSurvey.canonn.CodexRef.init(Boolean reset)
   at SrvSurvey.net.Git.refreshPublishedData()
07:35:05: isFirewallProblem?
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at SrvSurvey.canonn.CodexRef.loadCodexRef()
   at SrvSurvey.canonn.CodexRef.init(Boolean reset)
   at SrvSurvey.net.Git.refreshPublishedData()
```

**Comment by njthomson** [comment]
@KilrSkwerl - does this keep happening every time you start SrvSurvey? (Beyond 3 times after re-installing)

**Comment by KilrSkwerl** [comment]
It has stopped happening, can’t say how many times I have stopped and started the software. BUT now it says “wrong commander or the game is not active” even with Elite Dangerous running.

Sent from my iPhone

On Apr 5, 2024, at 12:22, njthomson ***@***.***> wrote:

﻿

@KilrSkwerl<https://github.com/KilrSkwerl> - does this keep happening every time you start SrvSurvey? (Beyond 3 times after re-installing)

**Comment by njthomson** [comment]
For that, check the cmdr selected in settings, top of the 1st tab. Choosing "any" is best.

**Comment by njthomson** [comment]
As for the initial `HttpRequestException` errors ... I do not control the server that is causing the problem, but I can make it not block using SrvSurvey where possible.

I'm curious if this problem only occurred whilst you were in a specific system?

**Comment by KilrSkwerl** [comment]
I was landed at Saunders Dive, in Wolf 1301, when it started.

While dinner was in the oven I was scrolling through the Guardian Science Corps #survey-general channel on Discord. A user named “grinning2001l suggested to another user experiencing similar issues to delete c:\users\<name>\appdata\local\packages\35333nosmohtsoftware.142860789c73f_p4c193bsm1z5a\localcache\roaming\srvsurvey\srvsurvey … IT WORKED!

Thank you for your quick responses. I love the app and have got a few of my wingers using it now as well.

Ready, aye ready.
CMDR KilrSkwerl
07

Sent from my iPad

On Apr 5, 2024, at 15:56, njthomson ***@***.***> wrote:

﻿

As for the initial HttpRequestException errors ... I do not control the server that is causing the problem, but I can make it not block using SrvSurvey where possible.

I'm curious if this problem only occurred whilst you were in a specific system?

**Comment by njthomson** [comment]
@KilrSkwerl - when you deleted that folder, do you remember if you had both `SrvSurvey` and `SrvSurvey-` folders?

**Comment by KilrSkwerl** [comment]
Yes, both folders were there.

Sent from my iPad

On Apr 5, 2024, at 17:09, njthomson ***@***.***> wrote:

﻿

@KilrSkwerl<https://github.com/KilrSkwerl> - when you deleted that folder, do you remember if you had both SrvSurvey and SrvSurvey- folders?

**Comment by njthomson** [comment]
Do you have a folder `%appdata%\SrvSurvey\SrvSurvey\1.1.0.0\` too?

(Meaning `C:\Users\abc\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\` not `C:\Users\abc\AppData\Local\Packages\35333NosmohtSoftware.142860789C73F_p4c193bsm1z5a\...`)

**Comment by KilrSkwerl** [comment]
Yes. That folder exists as well.

Sent from my iPad

On Apr 5, 2024, at 17:19, njthomson ***@***.***> wrote:

﻿

Do you have a folder %appdata%\SrvSurvey\SrvSurvey\1.1.0.0\ too?

(Meaning C:\Users\abc\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\ not C:\Users\abc\AppData\Local\Packages\35333NosmohtSoftware.142860789C73F_p4c193bsm1z5a\...)

**Comment by njthomson** [comment]
Excellent, thank you for confirming.

**Comment by njthomson** [comment]
This will be fixed as of build >= `1.1.3.7`

**Comment by njthomson** [comment]
Fixed in https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.8

**Comment by KilrSkwerl** [comment]
Awesome! I’ll update when I get home.

Sent from my iPhone

On Apr 9, 2024, at 18:31, njthomson ***@***.***> wrote:

﻿

Fixed in https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.8
