### ISSUE TITLE
SRVsurvey not starting

### ISSUE THREAD

**Issue by Hotpilot** [njthomson/SrvSurvey#92]
### What happened?

When I try to start SRV survey as before , I get a few turns of the Microsoft ''wait circles'' and nothing further happens. This is since about a week, possibly after a Windows 10 update, I do not remember that. I have tried deleting and reinstalling, both from the Github setup file and from the Micro$oft store, both with the same result. Until this started, I have been happily using SRV survey for months with no issues. I hate to do without, now. It is really good when it works.

### Version

Latest from Microsoft Store. I do not get to see the version number

### Exception message

No exception message. I am a simple user.

### Exception stack

No stack

**Comment by njthomson** [comment]
Thank you @Hotpilot for reporting, I'm hoping it is a known problem. Can you verify which of these folders exist on your computer?

`"c:\users\<name>\appdata\local\packages\35333nosmohtsoftware.142860789c73f_p4c193bsm1z5a\localcache\roaming\srvsurvey\srvsurvey"`

`"c:\users\<name>\appdata\local\packages\35333nosmohtsoftware.142860789c73f_p4c193bsm1z5a\localcache\roaming\srvsurvey\srvsurvey‐"`

`"c:\users\<name>\appdata\roaming\srvsurvey\srvsurvey"`


My suspicion is that you have all 3. If so, can you rename the first one to some other name, say `"xsrvsurvey"` - does this fix the problem?

**Comment by Hotpilot** [comment]
Thank you very much for the quick support.
The first folder does not exist. Down to roaming everything is there, but that roaming folder contains a folder "Microsoft" containing a folder 'Windows'  containing a folder Start Menu containing a folder Programs which is empty.

The second folder therefor does not exist either.

The third folder: down to SrvSurvey its there. Roaming contains a folder SrvSurvey containg a folder SrvSurvey containing an empty 1.0.0.0+6e etc folder which is empty and a 1.1.0.0 folder with program files.

I hope this helps. I have not tried the renaming because it is different from what you described.

Thanks for your time. Really appreciate it.
Peter, The Netherlands.

8 apr. 2024 19:17:07 njthomson ***@***.***>:

**Comment by njthomson** [comment]
You are correct not to rename anything - the folders you describe how things are supposed to be. (These issues are tricky as they do not happen for me locly, so it is hard to diagnose).

So to confirm: when you start SrvSurvey the app never appears? Even after removing and re-installing SrvSurvey?

**Comment by Hotpilot** [comment]
Correct. Even after removing and re-installing several times, same result. A few turns of the windows pause symbol and that is all. Now, there is something that may give you some clue. Before SrvSurvey stopped working as it does now, there were a few occasions that is started up, but in a completely minimalised window. Hard to find between app icons on the Desktop. I had never minimalised it myself so I found that strange.  I understand that it is difficult for you to reproduce. Let me know if there is something I can try. 
-------- Oorspronkelijk bericht --------Van: njthomson ***@***.***> Datum: 08-04-2024  23:08  (GMT+01:00) Aan: njthomson/SrvSurvey ***@***.***> Cc: Hotpilot ***@***.***>, Mention ***@***.***> Onderwerp: Re: [njthomson/SrvSurvey] SRVsurvey not starting (Issue #92) 
You are correct not to rename anything - the folders you describe how things are supposed to be. (These issues are tricky as they do not happen for me locly, so it is hard to diagnose).
So to confirm: when you start SrvSurvey the app never appears? Even after removing and re-installing SrvSurvey?

**Comment by njthomson** [comment]
If you see the icon on the task bar, but the window is not visible anywhere - you can reset the stored location with the following:

- With SrvSurvey not running, edit this file (in notepad is fine):
`"c:\users\<name>\appdata\roaming\srvsurvey\srvsurvey\1.1.0.0\settings.json"`

- Find and delete the line with `formMainLocation`.
    (Can you also share that line here, I am curious to see the numbers)

- Restart SrvSurvey

**Comment by Hotpilot** [comment]
I see your point. But to my surprise, the settings file is completely empty. Also empty when opening it with notepad.  And if I start SRVsurvey from the windows program menu, nothing in the settings file or tha directory changes. I have looked at the contentst of the speciesrewards file and they look normal to me but if I look at the file date, that is a file from the 15th of january,  long before SRVsurvey stopped working normal.
-------- Oorspronkelijk bericht --------Van: njthomson ***@***.***> Datum: 08-04-2024  23:48  (GMT+01:00) Aan: njthomson/SrvSurvey ***@***.***> Cc: Hotpilot ***@***.***>, Mention ***@***.***> Onderwerp: Re: [njthomson/SrvSurvey] SRVsurvey not starting (Issue #92) 
If you see the icon on the task bar, but the window is not visible anywhere - you can reset the stored location with the following:


With SrvSurvey not running, edit this file (in notepad is fine):
"c:\users\<name>\appdata\roaming\srvsurvey\srvsurvey\1.1.0.0\settings.json"


Find and delete the line with formMainLocation.
(Can you also share that line here, I am curious to see the numbers)


Restart SrvSurvey

**Comment by njthomson** [comment]
@Hotpilot did you try deleting just settings.json and re-starting?

After that I suggesting removing the whole folder:
`"c:\users\<name>\appdata\roaming\srvsurvey\srvsurvey\"`
... and then restarting.

**Comment by njthomson** [comment]
And to confirm: at this point when starting SrvSurvey, the main app window never appears for you, right?

Does the icon appear and remain in the taskbar?

**Comment by Hotpilot** [comment]
I have now deleted the settings file and yesss.. the app starts normal!
Tested on a planet surface and everything works. Thank you so much!
Any idea how the settings file got and stayed empty?

You wrote:
> After that I suggesting removing the whole folder:
> *"c:\users\<name>\appdata\roaming\srvsurvey\srvsurvey\"*
> ... and then restarting.
Is it still good to do that?

And to answer your second set of questions: no, I did not get a program window and neither did the toolbar icon activate.

Thank you again and where is the donation box? :)


9 apr. 2024 19:36:33 njthomson ***@***.***>:

**Comment by njthomson** [comment]
I'm not sure how it became empty - a very rare thread collision perhaps. But once it was empty, that would cause problems super early, before my code has a chance to handle any errors.

Knowing this predicament could now occur, I will add defensive code to handle it better in the future. 

Thank you @Hotpilot for your help getting to the bottom of this.

**Comment by njthomson** [comment]
This will be fixed as of build >= `1.1.3.6`

**Comment by njthomson** [comment]
Fixed in https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.8

**Comment by Hotpilot** [comment]
For your complete information: before you published the update, I restarted Windows 10, and the settings file was again empty!With the current version 1.1.3.8, this does not happen anymore. Thanks again for excellent user support.
