### ISSUE TITLE
Target distance not updating in 1.1.3.8

### ISSUE THREAD

**Issue by Hotpilot** [njthomson/SrvSurvey#93]
Since using 1.1.3.8, the distance to a set Target is not updating while in SRV. It updates when disembarking, but after that, again not while in the SRV. The arrow to Target keeps working all the time. I am using the newly released Github file. All other functions seem normal.

**Comment by njthomson** [comment]
@Hotpilot - to confirm: is it the distance in this overlay that is not updating?
![254469720-bcdbb7e5-bcc5-4528-966f-4dd7240f4459](https://github.com/njthomson/SrvSurvey/assets/3903773/5964f6ba-a40a-4c9a-973e-2661f6380f73)

There is a known limitation with how often the game updates the files read by SrvSurvey:

> The latitude or longitude need to change by 0.02 degrees to trigger an update when flying, or by 0.0005 degrees when in the SRV

Hence moving short distances will not trigger, however toggling head lights or the cargo scoop will cause those files to be updated immediately. Can you try toggling one of those and see if it makes a difference?

To help diagnose "stale file" issues like this, the little graph in the lower left corner provides a visual hint. It will go high when files are updated, then count down over 5 seconds:
![296520155-f35d5724-166b-474c-8e04-1c117acf14c1](https://github.com/njthomson/SrvSurvey/assets/3903773/9abe5f17-5a22-496f-9b35-b3d168063677)

**Comment by Hotpilot** [comment]
Yes, it is the distance in that overlay that is not updating. Not at all, while I am in the SRV. And I assure you that this was not the case in the previous version. 0.00005 degrees on a average body is about 5 meters, and in my experience that was indeed the update trigger. Now, I can drive 1000 meters or about 0.1 degree and the distance measurement does not change until I leave the SRV. I will check later what toggling headlights does when I am on a planet surface; I'm moving my carrier right now.

**Comment by njthomson** [comment]
Very curious indeed.

**Comment by Hotpilot** [comment]
I have done some further observations.

I set a target and started driving, about 300m. The distance to target stayed at 0 and that is not how it used to be. The arrow turned when I was making turns with the SRV, but observing more closely, I now saw that the arrow did not keep pointing to the target position but at other directions, suggesting that the arrow also is not correctly updated.

I then stopped the SRV and used to cargo scoop and headlights and the distance indicated stayed at 0. I then exited the SRV using the disembarkation screen; the overlay disappears while doing that but returns right after disembarkation with a correct value for distance (342m) and heading. 

I quit SRVsurvey, deleted the settings file and restarted but the behaviour was as written above. 
If there is something you want me to try, please let me know.

**Comment by njthomson** [comment]
Thank you @Hotpilot for your detailed report - I have observed the same. This will be fixed in the next build.

**Comment by njthomson** [comment]
@Hotpilot this is fixed in this build:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.3.11
