### ISSUE TITLE
SrvSurvey stopped working and now won't start

### ISSUE THREAD

**Issue by RJHnetka** [njthomson/SrvSurvey#97]
An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
  at SrvSurvey.Main..ctor()
  at SrvSurvey.Program.Main()

I don't know why it stopped working and don't have a clue as what the message means.
Thanks

**Comment by njthomson** [comment]
Thank you @RJHnetka for reporting this, are you able to get at any of the log files?

**Comment by RJHnetka** [comment]
I finally found where the program seems to be. When I click to start the blue circle pops up and then disappears. This is the last of 5 similar text files and I noticed it updated the time when I click on the program.  I found the program on ....user/appdata/roaming/SrvSurvey.  There are multiple folders with lots of json files but I don't see an ".exe" file which I would expect needed to start the program.  I searched through the "Program Files and Program files(x86) and couldn't find SrvSurvey which is were I would expect to find it. When it stopped working I uninstalled and re-installed from the Windows App Store if that helps.
[srvs-20240420_114753.txt](https://github.com/njthomson/SrvSurvey/files/15049430/srvs-20240420_114753.txt)

**Comment by njthomson** [comment]
@RJHnetka is it working properly after reinstalling? If not ...

Thank you for the log file above, it suggests there's something wrong with the settings file.

Could you share the file: `c:\Users\Bob\AppData\Roaming\SrvSurvey\SrvSurvey\1.1.0.0\settings.json`

**Comment by RJHnetka** [comment]
[settings.json](https://github.com/njthomson/SrvSurvey/files/15049864/settings.json)
I did the re-install prior to this attempt with you for help. Windows has stopped using Speech Recognition and now I keep getting "Voice Access" message across the top of my monitor. Could that have something to do with my problem?

**Comment by njthomson** [comment]
@RJHnetka SrvSurvey has nothing to do with Voice, but if you use Elite Copilot ... that does. I don't believe this has any connection to this problem here.

That settings file looks corrupted. With SrvSurvey closed, I recommend deleting it and then try again.

**Comment by RJHnetka** [comment]
Thanks very much much. I deleted that settings file. Clicked on SRV and it said this new version has to perform a data migration, which it did and then restarted. Thanks again. 👍🏻👍🏻Sent from my iPhoneOn Apr 21, 2024, at 1:46 PM, njthomson ***@***.***> wrote:﻿
@RJHnetka SrvSurvey has nothing to do with Voice, but if you use Elite Copilot ... that does. I don't believe this has any connection to this problem here.
That settings file looks corrupted. With SrvSurvey closed, I recommend deleting it and then try again.
