### ISSUE TITLE
Exception "Unexpected entryId: '2100802'" at 18/04/2024 0:08:54 +01:00

### ISSUE THREAD

**Issue by Minecrafter8001** [njthomson/SrvSurvey#98]
### What happened?

just finished scanning a planet and jumped out of the system

### Version

1.1.3.1

### Exception message

Unexpected entryId: '2100802'

### Exception stack

   at SrvSurvey.canonn.CodexRef.matchFromEntryId(String entryId)
   at SrvSurvey.canonn.CodexRef.matchFromEntryId(Int64 entryId)
   at SrvSurvey.game.Game.onJournalEntry(CodexEntry entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.Game.Journals_onJournalEntry(JournalEntry entry, Int32 index)

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1802","build":"r301217/r0 ","timestamp":"2024-04-17T19:32:40Z","event":"Fileheader"}
00:02:22: EVENT:departingBody, from Pru Euq ZH-Q c19-1 BCD 1 a
00:05:37: Mode change SuperCruising => SAA
00:05:52: Mode change SAA => ExternalPanel
00:05:55: Mode change ExternalPanel => SuperCruising
00:06:11: Mode change SuperCruising => ExternalPanel
00:06:17: Mode change ExternalPanel => SuperCruising
00:06:54: Mode change SuperCruising => ExternalPanel
00:07:00: Mode change ExternalPanel => SuperCruising
00:07:01: Mode change SuperCruising => ExternalPanel
00:07:02: Mode change ExternalPanel => CommsPanel
00:07:03: Mode change CommsPanel => ExternalPanel
00:07:07: Mode change ExternalPanel => SuperCruising
00:07:46: Mode change SuperCruising => ExternalPanel
00:07:48: Mode change ExternalPanel => SuperCruising
00:07:56: Mode change SuperCruising => RolePanel
00:07:57: Mode change RolePanel => ExternalPanel
00:07:59: Mode change ExternalPanel => SuperCruising
00:08:01: Mode change SuperCruising => ExternalPanel
00:08:04: Mode change ExternalPanel => SuperCruising
00:08:49: Opening link: (length: 681)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=Exception+%22Unexpected+entryId%3A+%272100802%27%22+at+18%2F04%2F2024+0%3A08%3A49+%2B01%3A00&what-happened=&versio
```

**Comment by Minecrafter8001** [comment]
the system is Pru Euq ZH-Q c19-1 btw

**Comment by njthomson** [comment]
Thank you @Minecrafter8001 for reporting this, let me see what I can find.

**Comment by njthomson** [comment]
@Minecrafter8001 - to confirm: the error occurred after arriving in the next system?

Had you been to any Notable Stellar Phonenom's at the time?

**Comment by njthomson** [comment]
Found the problem, this will be fixed in the next build.

**Comment by Minecrafter8001** [comment]
> @Minecrafter8001 - to confirm: the error occurred after arriving in the next system?
> 
> Had you been to any Notable Stellar Phonenom's at the time?

hey sorry only just saw this
yes i had been

**Comment by Minecrafter8001** [comment]
will be fixed in next update
